### ISSUE TITLE
convert hardware from proto to production

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#100]
- re-drill chassis board
- change all terminals to screw type
- fit case to Arduino/shields

**Comment by stevempope** [comment]
Name a date you are free and I am more than happy to participate. I presume the building will be at yours?

**Comment by SamanthaDawsonBanks** [comment]
yeah 2nd build day at mine, the build should be more streamlined this time.
date will probably be after MS2 so once we have shaken all the bugs out of the hardware design

**Comment by HarryWJackson1996** [comment]
Sounds like a good plan.
