### ISSUE TITLE
Radians or degrees 

### ISSUE THREAD

**Issue by HarryWJackson1996** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#102]
Hi, with regards to theta and phi do you want the angles to be returned in terms of Radians or Degrees?

**Comment by SamanthaDawsonBanks** [comment]
Probably degrees, but to be honest "steps"
https://www.adafruit.com/product/324

**Comment by HarryWJackson1996** [comment]
Ok no problem thanks.

**Comment by SamanthaDawsonBanks** [comment]
in the end it will be "steps" but that will be relative the length of the wheelbase and the circumference of the wheel see #20 for mega math
