### ISSUE TITLE
Reviewing Git Requests

### ISSUE THREAD

**Issue by stevempope** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#104]
Hi all, 

We need to talk about the rate at which Pull Requests are being reviewed.

Currently we have two open and I don't feel comfortable extending the requests until they are approved.

Our rules state that 3 of us, including the person filing the request, must have approved the request.

At the moment this is slowing bits down as we are not getting the reviews of the code.

I would like to suggest an amendment to the rule that if after 18 hours the code has been approved by 2 people including the requester, then the code can be merged without further input.

Thoughts?

**Comment by SamanthaDawsonBanks** [comment]
I don't like it as an idea as I feel it is taking us in a "less review" direction.
I would prefer to see us moving in a "more involved" direction?

**Comment by SamanthaDawsonBanks** [comment]
One issue with pr code review is that as code blobs get bigger it becomes less sensible to actually review the way the code works, it becomes more a case of code style and programming approach

**Comment by stevempope** [comment]
I don’t like it either, but I have a concern about getting finished and meeting our milestones

**Comment by HarryWJackson1996** [comment]
I have reviewed both pull requests and they have both been accepted. I agree they should be reviewed faster. Maybe a possibility is if we have any outstanding requests, if they are still open by Thursday, we can review it as a group and merge then and there (given its correct).

**Comment by stevempope** [comment]
We have agreed in meeting 01/03/2018 that Harrys approach will be used. PR creators must close their own PR's when approved.
