### ISSUE TITLE
AdHoc -> infrastructure WiFi on leader election

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#115]
as comment in #114 mcomp_Java/src/common/objects/Leader.java LN61

initial idea was to have bots wake > create an ad-hoc wifi network > make herd > elect leader > transition the wifi from ad-hoc to infrastructure

however this is; complicated, OS dependant, and for research stages mostly irrelevant.

we could lock it to an infra to start with or......?

**Comment by RyanShoobert** [comment]
It may be best to lock it to infrastructure to start with but this may cause other issues later. Will probably be best to discuss this one in person.

**Comment by SamanthaDawsonBanks** [comment]
yeah in person sounds good, in the mean time just leave it as a comment line and we can amend it later

**Comment by RyanShoobert** [comment]
Decided to set to infrastructure mode by default on the pis
