### ISSUE TITLE
Stepper Motor and "Blocking"

### ISSUE THREAD

**Issue by stevempope** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#117]
An issue that has been mentioned in passing is that we may run into a bottleneck when pulsing the stepper motors.

The problem potentially is that while driving in a very long straight line we may end up "missing" a large area of map that could have been taken with the LiDAR sensor.

The adafruit (creators of the motorshield) page references a library extension to their own which allows for running the motors in a non blocking manor. This may not benefit us this year but could help in the future.

Here is the link to their repo (It's referenced by the adafruit page and the description is in #33 )
https://github.com/adafruit/AccelStepper
Any thoughts?

**Comment by stevempope** [comment]
To be clear, in the current library, a call to the motors only releases resources when it completes the sets of pulses.

**Comment by SamanthaDawsonBanks** [comment]
yeah good point, at the moment you are calling the motor in a for loop with one step so we could check as part of that loop?

but separately we may want to send steps in 'batches' either way?

depending on how we hook the senses the non blocking might need to be done either way?

**Comment by SamanthaDawsonBanks** [comment]
I have tagged this as enhancement and for M3, just so we have context, but it maybe that for reasons of threading we want to stay deterministic and thus single and blocking

**Comment by SamanthaDawsonBanks** [comment]
Closed at answered - staying with blocking as it maintains deterministic state
