### ISSUE TITLE
mapLayer as a collection / linked list of cells

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#13]
with a 'cell' being an object with a x,y position and a n[3..] list of adjacent nodes

i'm having a data structure meltdown atm so need some more brains..... brains!!

**Comment by SamanthaDawsonBanks** [comment]
might just need to rubber duck[1] this out {engage the bear!!!}:

[bear was removed... it was unbearable...]

but we cant just use an array as they might drive off the edge and need to be expanded, arraylist would fix bigger but only in x+ and y+ not x- or y-

one option is to use an array and manually handle rebuilding but that is O(N) of total data set (map size not layer size)

so LL of cells would let me 'tickle' [tickle = process] only the ones that need to be done (have data)?? but that could mean one LL chain to the N and S (columns) with each line row bing a ll to the E and W on those chains??

[1] 23. Rubber Ducking. https://blog.codinghorror.com/new-programming-jargon/

**Comment by SamanthaDawsonBanks** [comment]
Pull a  starting GPS loc and have all cells xy as offset from start?

**Comment by stevempope** [comment]
We know how many neighbours each cell in a map will have, because we dictate the grid shape. Does this not mean that we can use an Array? Each cell contains itself and then (if a square) 4 pointers to arrays to it's North, East, South and West.

Maybe I am being silly. Needs more Rubber Duck.

**Comment by SamanthaDawsonBanks** [comment]
I'm concerned about the O() ramifications of different data structures:
an array of [linked] cells could result in O(n)
also adding a new 'low end' row could be an issue?
...still ducking...

**Comment by SamanthaDawsonBanks** [comment]
discussed and going with the nested arrays of vertex
