### ISSUE TITLE
is int 'long' enough

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#130]
as per the pun; in many places we are using int (and sometimes float), but for some of the cases the number being handled could be "large" other than cases that we are ***sure*** that it will fit consider converting the whole system to doubleWord length vars?

**Comment by RyanShoobert** [comment]
That is a good point that I neglected to think of. To argue the other side, there may also even be cases where we could make datatypes smaller (if we care that much and if it actually translates in javaland?)

To answer your question though, it may be advisable in the cases where we can't be _**sure**_ that it won't overflow.

**Comment by stevempope** [comment]
Ryan is right I think, we should probably only use the smaller data types where we can mathematically say we will never overflow.
