### ISSUE TITLE
refactor waypoint from int to double

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#14]

**Comment by SamanthaDawsonBanks** [comment]
WP is currently int x, int y. but I need to do some maths to it that result in real numbers. i think it should have always been a double just checking for sanity??

**Comment by stevempope** [comment]
Are you thinking of accepting decimal values to not lose accuracy? Or are you thinking of using integers to keep the calculation less processor intensive?

I think if we are to include decimals we agree on a level of floating point accuracy, maybe 3 decimal places. Any smaller and we risk a very intensive grid mapping process. For instance, if a return is more accurate than a grid, we may end up shading 2 areas on the grid when 0.001% of that area is shaded.

The size of the return dataset should really be a factor in considering grid density.

**Comment by SamanthaDawsonBanks** [comment]
yeah most of this is what i was thinking but also i need to rotate them:
newX = oldX * cosA - oldY * sinA
which results in a very non int number

**Comment by stevempope** [comment]
Issue resolved by pull request #21
