### ISSUE TITLE
Scalability

### ISSUE THREAD

**Issue by RyanShoobert** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#153]
Consider data as herd size increases

**Comment by SamanthaDawsonBanks** [comment]
As herd data sizes get bigger do we want to keep handing the herd as the var for a method or is it better to use the local (possibly out of date) copy?

**Comment by stevempope** [comment]
It's probably best to use the live copy and default and have a refreshed copy provided for local use in case of disaster. That said if we can guarantee that the Herd member will always receive an up to date copy there is no reason why the local Herd can't be used.

**Comment by SamanthaDawsonBanks** [comment]
this has mostly been sorted by the local herd data cache
