### ISSUE TITLE
Project Handover Document

### ISSUE THREAD

**Issue by CFuterman** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#154]

**Comment by SamanthaDawsonBanks** [comment]
A description of the process by which the project was approved, and the business case for undertaking the project.
A summary of the project execution, including whether the project met its objectives.
Details of the project’s budget performance and timeline performance.
A list of factors that affected the project results.
If possible, a description of the financial impact or other benefits the project will provide.
Attachments or appendices containing summaries (or the full text) of important project documentation, such as the scope document, project plan, test results and final approval/acceptance.

**Comment by CFuterman** [comment]
Got the last little bits to write up that we discussed in the last meeting. I will close the issue as and when it is completed

**Comment by CFuterman** [comment]
I have completed this, and it is ready to be read over tomorrow in our meeting.
