### ISSUE TITLE
Extensibility/Interoperability

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#163]

**Comment by CFuterman** [comment]
Steve - Lead
Dave / Ryan - Secondary

**Comment by RyanShoobert** [comment]
@HarryWJackson1996, you said in the last meeting that you were interested in helping with this. How is it coming along?

**Comment by HarryWJackson1996** [comment]
well i have only considered extensibility from a pathfinding/heuristic point of view, all my stuff will be done by Wednesday, prior to fridays submission

**Comment by SamanthaDawsonBanks** [comment]
remember (all) that we are aiming to group spellcheck and compose the doc on Wednesday for final fixes (and I do mean fixes not still writing) on Wednesday night / Thursday morning

this is so we can get it printed etc etc

**Comment by SamanthaDawsonBanks** [comment]
c7 sectioned off in to the individual sections
