### ISSUE TITLE
Non cardinal driving from cardinal pathfinding

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#167]
While the vertex based nature of the map will produce a cardinal direction, the relation between three nodes (convective path) nodes will produce a right angle triangle(ABC), and the two end most cartesian points (A->C) will form a vector.

If the nodes along that vector (the hypotenuse of the previous triangle) are also empty the path can be simplified by removing the middle node (B) and the robot can simply drive at a non cardinal angle

Assuming any of that makes sense?

**Comment by stevempope** [comment]
For each triangle, we would need to check that its nearest 5 neighbours in the Y direction of travel is also free (30cm body width, 5cm grid) so that we can "cut" that corner?

**Comment by stevempope** [comment]
Also, how would this work with simultaneous changes in direction, such as left-up then right- down?

**Comment by SamanthaDawsonBanks** [comment]
For simultaneous changes each threepul would need to be considered individually, but if a threepul was able to eliminate its B (of ABC) then it would be a tuple and if the optimisation was run recursively then the npull A!BCD would become the next threepul (ACD) and C might be eliminated
