### ISSUE TITLE
Document Code

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#17]
Document Code (javadoc etc)
as we go or every x weeks?
could be a job for someone that is not busy?

**Comment by stevempope** [comment]
I am quite happy to go through and comment the code. I do feel we should all be doing this though, it will help being able to explain what each method is for when it comes to the final Viva.

**Comment by SamanthaDawsonBanks** [comment]
*Bump* can everyone [mostly me] check that their code has appropriate comments and any TODO/FIXME  [again mostly me] are current

**Comment by SamanthaDawsonBanks** [comment]
//DONE:
J
Datatypes (subject to merge issues) except for MapLayer (as it have changed too much in the upcoming PR #172 )
Interfaces

//TODO:
path
maplayer
vertex

//CHECK:
Joinable - acceptMember and requestJoin - same for leave
Notifiable - Drawable - same thing?
becomeLeader return type / life-cycle
updateable.updateModel - probably needs separating into actual calls ("member now at loc".....)

//QUESTION:
what ability does a member have to be suitable to become a leader (promotable interface) is it PROCESSOR? if so there is overlap?
