### ISSUE TITLE
Readme file and License Standards

### ISSUE THREAD

**Issue by CFuterman** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#173]
A document that I will be completing myself. I may need some assistance from the rest of the team as this is something that I have not completed before.

**Comment by SamanthaDawsonBanks** [comment]
No worries mate, i'm happy to take secondary on this and provide technical guidance; as a start:

readme.md {there is probably a template somewhere}
https://gist.github.com/PurpleBooth/109311bb0361f32d87a2
https://github.com/dbader/readme-template
https://gist.github.com/zenorocha/4526327

licence (might need to loop in Saeed on that one)
https://choosealicense.com/
https://www.gnu.org/licenses/license-recommendations.en.html
http://www.dcc.ac.uk/resources/how-guides/license-research-data

**Comment by CFuterman** [comment]
License standards document is complete and can be found on the OneDrive. The readme file was something that I haven't been able to get round to today, if two of us work on it tomorrow, I feel this can get completed quicker
