### ISSUE TITLE
Assign sizes to datatypes

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#174]
the Map, WP and AD both make use of sizes but there is no definition of what 1 *is*

**Comment by SamanthaDawsonBanks** [comment]
this one loops round to #33 as the sensor and grid size are all real world measurements

**Comment by stevempope** [comment]
We discussed 5cm being the base unit, so I guess that gives us the scale of 1 = 5cm, 2 = 10cm and so on.

When we collect AD's, its probably best to convert them from raw mm into this so that the Waypoints and Maps don't have to do any post processing.

**Comment by RyanShoobert** [comment]
The lidar sensor returns data in cm and mm and requires scaling once returned so that 0.2 = 5cm.
