### ISSUE TITLE
Stepping through the Motor code

### ISSUE THREAD

**Issue by stevempope** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#182]
Upon review of the Unit test data we may need to review the maths that surrounds drive to make sure our variables are accurate. This will be completed at the next hardware day.

**Comment by SamanthaDawsonBanks** [comment]
could be an overflow, what data type are we using?

**Comment by stevempope** [comment]
So the issue is our use of an int for the step value, giving a signed max of 32,000 step or about 330 revolutions of the wheel. The suggested fix is to change the type to an unsinged long to drastically increase the maximum steps in a single request. Marked for refactor.

**Comment by stevempope** [comment]
So forward is currently a signed long and rotate is a double

**Comment by stevempope** [comment]
Ok so I have an answer for our issue.

The number 10,000,000 is well within the limits of a signed long and indeed a double in Arduino C, but to calculate the value of hypot(double x, double y) we would have to hold for a very brief time the result of 10,000,000 squared and added to 10,000,000 which results in a massive overflow of the function and hence the first test does not move. I will have to follow up with some maths for what the limit is that we can ask for from the system but for now we at least know why.

For reference, on any Arduino MEGA based boards (uno, mega etc) a double will not be any longer than a float, remaining at 4 bytes. Only on the DUO board will a double produce an 8 byte (and therefore large enough) number.

**Comment by stevempope** [comment]
So the result would be 200,000,000,000,0000 which with a floating point is more than 6 bytes long.

**Comment by SamanthaDawsonBanks** [comment]
there might be a way to do it with similar triangles? 

100*(sqrt((a/100)^2+(b/100)^2)) ≡ sqrt(a^2+b^2) 
x*(sqrt((a/x)^2+(b/x)^2)) ≡ sqrt(a^2+b^2)

**Comment by stevempope** [comment]
So the potential maximum in a signed double should be 1,073,741,823.0 which the root of is 32,767 so that is the physical limit we can ask for on the hardware we have. Before I close the issue do we want to make any data type changes to data types?

**Comment by SamanthaDawsonBanks** [comment]
I'm happy with capping the call (guarded both ends) [so that J will split big calls, and C will reject {do nothing?} big calls]
maybe factor the value out to the config and ref it [do we ref it on the J side as well?]?

**Comment by stevempope** [comment]
Sorry Dave just read your post. That is certainly possible but I am trying to think that for the sake of research recommend the duo as a production board. 32,767 into drive ends up with 218,446 steps taken which results in 1092 revolutions or 343.2 meters in a single call.

**Comment by stevempope** [comment]
I do need to refactor drive slightly to accommodate the potential size of the steps

**Comment by SamanthaDawsonBanks** [comment]
1092 rev = 343.2m?
I'm getting a different result

**Comment by stevempope** [comment]
My maths may be faulty...

**Comment by stevempope** [comment]
What did you get instead?

Other than the dodgy max amount of distance travelled (I did 1092 revs * 31.42 which is the value in robot config and as that is in cm divided by 100 for meters)

**Comment by SamanthaDawsonBanks** [comment]
ah my bad I think the value in config was a placeholder until the wheels were picked

**Comment by SamanthaDawsonBanks** [comment]
yeah bad (stale/dummy) data in the config 
6 inch (diameter) wheel [as sold so might be inc or ex tire]
gives 0.478779m circumference
0.478779 * 1092 = 522.826668m

**Comment by stevempope** [comment]
Right so thats fine, just need addressing in a PR, I will add it to #193

**Comment by stevempope** [comment]
#193 is closed so this should close with it. I am happy that the logic is correct.
