### ISSUE TITLE
Member (+view) Leader Herd Lifecycle method chase

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#195]
I could do with some help (and a lot of whiteboards) to track the MVLH interactions it will be a lot easier with more brains on the task, is anyone available for a modelling and coding session this week?

maybe Monday / Tuesday?

**Comment by stevempope** [comment]
Monday morning works for me #194 has been approved on the basis that we are whiteboarding it to completion

**Comment by HarryWJackson1996** [comment]
I'm around all week, and travel is no problem. I'd be happy to help where I can.

**Comment by stevempope** [comment]
Boards from Herd Chat to follow

**Comment by stevempope** [comment]
![wp_20180416_09_35_44_rich](https://user-images.githubusercontent.com/20892974/38870375-8b644248-4245-11e8-8cb1-169572dd496d.jpg)
![wp_20180416_09_45_52_rich 1](https://user-images.githubusercontent.com/20892974/38870377-8b8a8764-4245-11e8-8daf-4ad1f180b37b.jpg)
![wp_20180416_09_45_52_rich](https://user-images.githubusercontent.com/20892974/38870378-8ba7b01e-4245-11e8-86e0-e60249a4cdff.jpg)
![wp_20180416_10_16_25_rich](https://user-images.githubusercontent.com/20892974/38870380-8bc3970c-4245-11e8-9522-6f0e9407e7b0.jpg)
![wp_20180416_10_53_12_rich](https://user-images.githubusercontent.com/20892974/38870381-8be224c4-4245-11e8-9e98-1e22d565921b.jpg)

**Comment by SamanthaDawsonBanks** [comment]
much of this is done and the rest is on the list of bits to do
