### ISSUE TITLE
Methods still requiring work

### ISSUE THREAD

**Issue by stevempope** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#197]
Place your initials next to these remaining methods if you are able to work on them (after you have finished any current work)

DA - Method in Member that allows the Member main class to go to sleep/exit when finished (set awake to false)

DA - Same as above for View

DA - Same as above for Leader

DA - Simplify Member joining/leaving contact with RMI to register and deregister

DA - Test notify and get state between Leader and Member

DA - Expand stubs for things changing in the member etc

DA (partial) - Write Leader.go (Sense, Take Dest, Map, Pathfind, produce path and drive to locations)

- Ensure view has a notify/getState loop

DA (partial) [awaiting pipe and compass maybe GPS?] - Member needs to derive an absolute location value/which way it is facing for where it is using the compass.

HJ - Add GO button to GUI

DA - Leader.go performs Leader.pathfind

DA - Leader.go causes multiple calls to drive with each driver called

DA - Return from drive should trigger another LSense /maybe in go loop

- GUI should show when destination reached

- GUI should show if bot comes across a lidar invisible object (US test)

- Interface refactor (squash irrelevant interfaces)

RS - Map to ArrayList needs adding

DA - Adjust leader to have better access methods for herd stuff

DA - Update the electLeader method to choose from members with the processor ability

- Consider merging the interfaces processable and promotable

DA - Add to leader.register 
If global herd is null, get data from incoming member, 
always notify of change, each member/view will need to get state from the leader

DA - Connect RMI will no longer override local leader

DA - Override local herd leader and use local leader??
[DAVE: pretty sure this is backwards but I may be asleep]
"Remove localleaderref and use localherd.leader"

- There will need to be a Herd constructor for views

- In the GUI, there will need to be a method to repaint the screen after the notifyChange -> getState method

DA - Leader.register will need a call for sensing (if a sensor)

- Leader.register will need a call for obtaining the members location from the compass
[EDIT DAVE] "oh yes Dave, get a location from a compass; do it every day... heading from compass; loc from GPS (MS5)"

DA - As herd data will be sent via RMI, it will need to implement the Remote/Serializable interfaces

DA - Drive and sense need to add data to the model

RS (partial) - On all RMI exceptions, if a member is uncontactable, deregister it (assume it is lost/dead)
If it is the leader, run an election
[DAVE: we need to think about this one and whether to handle (try, catch, deregister) or throw up the line]

DA - Check the drive methods return handles for a lidar sense

- Button on the GUI that will start the pathfinding after a destination has been set

- Ensure that the GUI updates when we arrive at a waypoint, sense, repathfind etc.

HW - Addition of a button on the GUI which will shut down each member

HW - GUI needs a members box with a button which will display its abilities when clicked

HW+DA- GUI currently using getMap which is not implemented in herd
[DAVE: yeah the protection changed to 'protected' we need to look at the packages at some point that should then fix the access]

RS - Drive and sense methods for the member

**Comment by SamanthaDawsonBanks** [comment]
remember can people tag stuff on here when they START the task or we could have many people working on the same thing and thus wasting time

[Thread Edited to compress posts]

**Comment by SamanthaDawsonBanks** [comment]
this was auto closed but some minor bits will need to be done in the background

I will try to sort them into needed/MS5 so we know what we need for demo day

**Comment by SamanthaDawsonBanks** [comment]
harry i know you have been working on the gui how many of these bits are being worked on / done?

**Comment by HarryWJackson1996** [comment]
I did a commit yesterday with added functionality

**Comment by HarryWJackson1996** [comment]
the Go button was done, killMember and runtime exception for leader

**Comment by HarryWJackson1996** [comment]
should i do a PR for the A* updates and GUI?

**Comment by SamanthaDawsonBanks** [comment]
yeah if it is ready then PR it, can you also go through the list and tag then bits you have done so we can see what still needs to be done plz
