### ISSUE TITLE
Rotate map or robot

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#20]
all LiDAR returns will have a '0' value of in front of them (hopefully) so as the robot rotates that will no longer be 'north'

we need to either:

rotate every return
or
rotate the map when a bot turns

there are pros and cons to both (about 50/50 i think), I have a preference but reserving it till comment are in...
discuss...

**Comment by stevempope** [comment]
I believe we need to rotate on every return.

The advantages of doing so are:

- We are rotating a maximum of one data set each time, keeping processing in real-time quite low. This is important in smaller herds with less processing power.

- This approach is "functional" in its style, meaning an incoming layer does not cause a change to any of the other layers in a map. The rotated layer is then added to the amalgamated grid at the right angle.

- Multiple robots can be used to retrieve LIDAR information without having to have multiple robots providing returns while all aligned at exactly the same angle.

There is a consideration though:

- We will need to have more storage to track the angle and turns taken at each step by a robot. This will allow us to retrace steps, though.

**Comment by SamanthaDawsonBanks** [comment]
assuming rotate return (robot) that means that each robot (actually each drivable) needs to track its ϴ (theta) and (x,y) offset [for equivalent translate issue]
i'm currently thinking:
ArrayList int drivable.getRotations();
ArrayList int drivable.getTranslations();

but that questions:
int vs double (do we need less than a degree?, probably not but stepper is 1.8 degree steps so we might end up with non int rotations??)
total vs list??

**Comment by stevempope** [comment]
I envisioned a running total as an xy pair for the translation. That way, if we are recording the turns taken, you could "subtract" from the total to trace back along the path.

rotations should be a double if we are having steps of 1.8 degrees. Otherwise we lose either 0.8 or 0.2 degrees for every rotational step we take.

**Comment by SamanthaDawsonBanks** [comment]
running position (translation) makes more sense, same logic applies to bearing (rotation) good call :)

as for int vs double its a bit more complicated than that:
the motor has 1.8 degree steps but that won't be 1.8 degree robot rotation [math to follow] so the question would be clarified as; do we care about greater than 1 degree of rotational accuracy?

[begin overly long math blah]
there are two ways we can rotate the robot:
one wheel stationary and one turning 1.8 degrees which will result in the pivot point being the other (stationary wheel) this would result in some forward or backwards movement and this is sub-optimal
or:
one wheel rotating 1.8 degrees clockwise while the other goes 1.8 counter-clockwise this results in a pivot point at the 'centre' of the robot the robot 'turning in place'.
assuming that we go for option 2
we now calculate the movement from that 1.8 degrees...
taking the circumference of the wheel, dividing that by 360 and multiplying by 1.8 we get the length of the arc on the end of the wedge 'm'
assuming a 5cm radius (circumference ≈ 31.42cm) 1.8 degree turn ≈ 0.1571cm. so m 0.1571cm or 16mm 
and the length of an arc, vs theta, can be calculated if you know the distance from the pivot (centre of robot) if we go with a robot that is smaller than the others so about 36cmx36cm then the distance from pivot would be 18cm {the answer will be typically be in radians so you convert}
but for each pulse (1.8 degrees) of the stepper a 36cm robot will turn 0.50006 degrees but even that assumes perfect traction etc

**Comment by SamanthaDawsonBanks** [comment]
![2017-12-14-17 06](https://user-images.githubusercontent.com/25463297/34006011-c3dff476-e0f4-11e7-80d9-6a3c8b67f72e.png)

**Comment by stevempope** [comment]
I agree with the second option for rotation. 

Purely for the sake of sanity, rotation against a central point means that we do not have to apply a second small translation to the map. 

As the single step provides as close to half a degree as possible, we should agree on two bursts from the motor, amounting to 1.0012 degrees of turning. The compass unit could be used to determine if we ever perform enough rotations to cause an error greater than a degree, and correct it.

**Comment by SamanthaDawsonBanks** [comment]
Sounds like a plan
