### ISSUE TITLE
To do list for meeting with Saeed 26/04

### ISSUE THREAD

**Issue by CFuterman** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#200]
So that we don't fall behind and give ourselves too little time to complete the final documentation. I want from everyone to have made a good start on this. 

- On the final documentation - Anyone who is a lead for any aspect of the final documentation. Can we look to have made a good start on this so that this is there to show Saeed next week. For the week after, the secondary to these to have looked over what has been written and add what they can. This way we will have one more week to complete this document. 

A quick reminder who is a lead on what is listed below. 

Use/business case - Charles
Provability/security - Steve
Mapping - David
Heuristics/Algorithms - Harry
Communications/RMI - Ryan
GUI/UX/Usability - Harry
Extensibility/Interoperability - Steve
Ethics - Steve
Project Handover - Charles
Readme and Licence - Charles (on this one, i will need to discuss with David on thursday's meeting as i'm still slightly unclear of what it is i need to do for this)

- Process Logs to be up to date 
- Implementation Plan - Charles

If this request is going to be too much work for some people, please comment below and we can work out any problems from there.

**Comment by SamanthaDawsonBanks** [comment]
Ah i have been tagging stuff at #200 when it should have been #197 sorry for the cross posting

**Comment by SamanthaDawsonBanks** [comment]
How are these coming?
I have a framework in my doc that might help people see what structure I am thinking for my and Ryan's section

**Comment by stevempope** [comment]
I have seen the framework and have placed my work so far on the LiDAR document in the same folder as the final document.

Once the LiDAR documentation is done I will be moving onto the main sections. I know its not a ‘critical’ document, especially when considering the final document, but I thought it best to get it done while it was still fresh in my head. We have spent a lot of time on the hardware side of things recently and it leads my train of thought nicely into provability.
