### ISSUE TITLE
PRs & Branches

### ISSUE THREAD

**Issue by RyanShoobert** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#211]
As time goes on, branches become stale and become harder to merge. Can everyone please check that any outstanding branches that need merging get PR'd or deleted if they have been already.

**Comment by SamanthaDawsonBanks** [comment]
good catch; I have checked and cleaned mine

**Comment by stevempope** [comment]
I have just the one branch open but it should be available for PR by 12pm tomorrow and can then be deleted when merged.

**Comment by SamanthaDawsonBanks** [comment]
still three branches open?
 main_C_v1 Updated 2 days ago by stevempope
PathfindFixes Updated 2 days ago by HarryWJackson1996
AStar3 Updated 16 days ago by HarryWJackson1996

**Comment by SamanthaDawsonBanks** [comment]
I assume these are dead? if not they will be stale one iis 92 commits behind

main_C_v1 Updated 5 days ago by stevempope
PathfindFixes Updated 5 days ago by HarryWJackson1996
AStar3 Updated 19 days ago by HarryWJackson1996

**Comment by SamanthaDawsonBanks** [comment]
Harry / Steve can you check your branches plz

**Comment by SamanthaDawsonBanks** [comment]
...

**Comment by SamanthaDawsonBanks** [comment]
branches cleared up
