### ISSUE TITLE
Code Freeze

### ISSUE THREAD

**Issue by RyanShoobert** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#212]
As we head closer to the final hand-in date, documentation needs to become a priority. I'm currently thinking that it may be best to have a code freeze for the next two weeks as of Thursday 19 April to enable use to concentrate on documentation and potentially finish up any bug fixes if we get done ahead of schedule.

**Comment by SamanthaDawsonBanks** [comment]
Sounds like a good idea, even if we don't freeze the code it would be good to really focus on the docs

**Comment by stevempope** [comment]
I agree. There are two things in code that I have in progress that I would like to finish as they work in tandem with the first bits of documentation, so these will be up latest 12pm tomorrow, would this be ok?

**Comment by RyanShoobert** [comment]
Yeah that shouldn't be a problem. If you're most of the way there with it (as I recall you saying you were) then it will be much better get it into the main branch then to leave it hanging (which also will partly address #211)
