### ISSUE TITLE
Poster Ideas

### ISSUE THREAD

**Issue by CFuterman** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#219]
Would be good to have something on everyone's aspect of the project. Diagrams and anything you think will be good to have on there, please put on here so that I can draw something up for next week's meeting (Thursday 3rd May 2018).

**Comment by CFuterman** [comment]
I am planning on making a start on the poster on Monday/Tuesday based on when I've made good progress with my other deadlines. I have noticed on the OneDrive that there is already a file for the poster. Which software is being used for this, and is it available for mac (otherwise i can't start until i get back to Brighton, looking like starting it Wednesday)?

Secondly, so that I have put the correct pictures on the poster, can the final pictures be posted on here to help on that front. Thanks! Hope all is going well with the final documentation sections.

**Comment by SamanthaDawsonBanks** [comment]
All sounds like a plan, the file is a Adobe Photoshop file, set up for print (CMYK, 150DPI, ISO 300%, with black = 75,68,67,90)

**Comment by CFuterman** [comment]
Perfect. I will download the trial of it on my mac tomorrow as I am out with the family today, and will make a start on it tomorrow.

**Comment by SamanthaDawsonBanks** [comment]
coolio I will probably put some placeholder blocks on the file for what I am thinking but we can always move stuff around when we meet up next

**Comment by SamanthaDawsonBanks** [comment]
![poster](https://user-images.githubusercontent.com/25463297/39672114-e8d083c6-511b-11e8-9a0b-29b8b2383637.png)

rough starting idea?

**Comment by RyanShoobert** [comment]
That looks like a good start to me @DavidAveryUoB

**Comment by stevempope** [comment]
Dave, that looks fantastic. If we are going to use the images of last years bots though, we probably should save one of the first boxes for a decent res picture of this years iteration.

Really like this. Headings wise I was thinking:

-Persistence
-Pathfinding
-Sensing and Driving
-Use Cases
-Map performance
-Modularity

Then one in the middle with the current hardware, not in any particular order.

**Comment by SamanthaDawsonBanks** [comment]
well if we can get a good pic of all 4 bots it would be cool to swap the bg pic out for that new bot as center stage?

**Comment by SamanthaDawsonBanks** [comment]
Right; So... it was poster day for PABS today, and we had a quick look at what can go on a poster and how it looks, finding are:
- we probably need more content (especially if we go for this size) [there is a question of if we want 4 {size reasons} or 5 {group members} separate posters ???]
- we probably need more text and smaller images / graphs

**Comment by SamanthaDawsonBanks** [comment]
if we do go with the 2A0 then each of those rounded rectangles is about A3 in size

**Comment by SamanthaDawsonBanks** [comment]
comments? drafts?

**Comment by SamanthaDawsonBanks** [comment]
change of plans poster is now poster(s):
1 for mapping and data-types
1 for path-finding and GUI
1 for comms and herd
1 for driving and sensing
all please remember that the posters showcase the work so also include a section to business stuff (unless you want a separate poster for that Charles?)
A1 setup for print (CMYK, 150DPI, ISO 300%, with black = 75,68,67,90) see blank file in OD

**Comment by SamanthaDawsonBanks** [comment]
![postera1](https://user-images.githubusercontent.com/25463297/40063789-00e51508-5856-11e8-8cc1-5e0503c97df6.png)
still not sure about the text size (i think the content text is too big and we wont get enough words in) [??comments from anyone that fas seen the other posters??]

**Comment by SamanthaDawsonBanks** [comment]
template file is in OD

**Comment by stevempope** [comment]
I think the template you put up looks perfect.

We need our Posters printed by Tuesday at the latest.

Would you like me to take a photo of the collection of robots on Tuesday, or are you happy for that background and to have a more modern picture in one of the frames?

I was going for hardware and provability, so that probably makes sense to have a hardware picture on board?
