### ISSUE TITLE
Viva Presentation 14/05/2018

### ISSUE THREAD

**Issue by CFuterman** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#220]
Initially, we need to come up with a day that we can make a start on the preparation of the Viva presentation. 

Can everyone please say the days that are good. 

Monday I have work at 6, so will need to be finished by 3.
Wednesday I'm working all day, so I can't be there.

**Comment by SamanthaDawsonBanks** [comment]
tuesday?

**Comment by CFuterman** [comment]
My original plan was to be back in brighton on Monday, but as it's a bank holiday, trains were all over the place. Won't be back until late Tuesday. I'm good for Wednesday, Thursday and Friday

**Comment by SamanthaDawsonBanks** [comment]
Your not working wed?

**Comment by CFuterman** [comment]
I'm working from 6, so from early until 4ish

**Comment by RyanShoobert** [comment]
I'm good for Wednesday, Thursday and Friday as well

**Comment by stevempope** [comment]
Wednesday Thursday Friday suits me down to the ground. Thursday and Friday are not limited by time, so I am envisioning some form of late evening work.

**Comment by SamanthaDawsonBanks** [comment]
well from a "lots to do; limited time to do it" point of view as much useful time together would be good

**Comment by SamanthaDawsonBanks** [comment]
thursday then early ish?

**Comment by CFuterman** [comment]
After the meeting with Saeed? I'm free all day, no work in the evening for me
