### ISSUE TITLE
Maths Sanity check

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#221]
there are several points in the docs that have some maths where dropping a decimal would make a major change to our findings so; if you have any maths that needs checking please post it here (probably a reference to the file rather than the maths itself) so it can be cross checked

**Comment by SamanthaDawsonBanks** [comment]
CH2 [somewhere (Steve asked for some maths to be checked)]
CH4 [somewhere (I know Harry asked us to check some bits)]
CH3 PG 9-11 Big O classification of storage and work

**Comment by stevempope** [comment]
Yeah so from C2, I wanted to double check the numbers I have used for the scale of the map. I am giving and example of us proof testing our model on whiteboard before we program.

I went for 10 orders of magnitude performance gain from reducing the grid density, and 5 orders of magnitude performance loss from a 100 times faster laptop taking 90 seconds to process. I believe this to be correct but I also don't want to explain in too much detail and step on the mapping section.

**Comment by SamanthaDawsonBanks** [comment]
looks like we need a maths appendix can people start to compile there math bits plz

**Comment by HarryWJackson1996** [comment]
yeah, as the hand in is friday and we should aim for wednesday to pull it together and review the work as whole. this includes double checking the maths etc.

**Comment by SamanthaDawsonBanks** [comment]
maths to be check during Wednesday meetup
