### ISSUE TITLE
Circle theory tidy up

### ISSUE THREAD

**Issue by stevempope** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#223]
So there are some optimisations/fixes I would like to make - List is here for sanity checking:

- The arc length of a single pulse can easily be calculated by: Theta * pi/180 * Wheel radius rather than 2 pi r for circumference then * 1.8.

-Logic needs to flip if we are not simplifying the above. 1.8 is 360/200 not 200/360.

**Comment by stevempope** [comment]
Further correction, it should be 2*pi*r divided by 360/200

**Comment by SamanthaDawsonBanks** [comment]
rmi test branch
