### ISSUE TITLE
Restarting path-finding with new data

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#232]
as the path-finding could be restarted (expanded map, interrupted op, lidar invis, bigger herd) there could be a case where areas were searched / evaluated multiple times.
but as we are storing the "searched space" AKA closed list could we just load the closed list then restart again?

separately (but related) if searched can be paused and resumed could that go one to be the bases of some form of parallel opt?

**Comment by HarryWJackson1996** [comment]
yeah it would be a good idea if we restarted the pathfinding we assess what we already know and only expand whats necessary?
