### ISSUE TITLE
Final M4 Jobs List

### ISSUE THREAD

**Issue by stevempope** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#236]
- [x] State of the Art
- [x] Headings in Provability
- [x] Conclusion
- [x] Reflection
- [x] Group communication
- [x] Tools used
- [x] Introduction

- [x] Abstract
- [ ] Update Lexicon of terms
- [x] Citations in Ethics

- [x] Appendix references in Ethics

- [x] Headings in Ethics

- [x] Yellow text in Ethics

- [x]  Citations in Provability and Security

- [x]  Steve check appendices

- [x] Parts List

- [x] Attach ultrasound cables

- [x] Push trinket code

- [x] Attach power supplies

- [ ] Fix wheels

- [ ] Poster contents

- [ ] Viva preparation

- [x] Finish proof reading A* Harry

- [x] GUI section Harry

- [x] Citations for GUI

- [x] Finish proof reading Ryan sections

- [x] Harry progress log - check dates

- [x] Charles process log

- [x] Steve, Dave and Harry Implementation plan sections

- [x] Hardware appendix - Design and Build?

- [ ] Charge battery

- [x] Dave Mapping appendix

- [x] Dave progress log

- [x] Project Management?

- [x] Charles Implementation Plan?/Handover Document?

- [x] Pull final document together

- [x] Diagrams and figs to pull together

- [ ] Push to release!

- [x] Code Dump Appendix

- [x] Heading names

- [ ] Readme

- [ ] Executive Summary

- [ ] task aloc chart?
--M5--
- [ ] #197

**Comment by CFuterman** [comment]
@DavidAveryUoB is the parts list up to date on the issue with the parts?
