### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by stevempope** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#238]

**Comment by stevempope** [comment]
Pathfinding and navigation research can be a costly task, with production quality Autonomous Vehicles using hardware estimated to cost $50,000(reference 1 #249). To test new ideas effectively, a design for a scalable approach is required. Attempts at a low cost pathfinding platform have been attempted by other research teams (reference 2 #249), but the implementations are specific to the research hardware, require relatively expensive hardware such as a laptop to function. 

In 2018 our MCOMP cohort were tasked with extending the cumulative work of previous cohorts work into robotics. We effected this by developing an implementation of a pathfinding robot for less than £400. Our work assessed the issues with the existing state of the art and delivered a modular framework for pathfinding that is highly scalable, extensible and remains effective when using embedded devices.

**Comment by stevempope** [comment]
Arc for introduction should be:
-Robotics research can be expensive and requires expertise in a variety of areas
-We were handed an iterative robotics project and told to extend it further
-We realised it would be advantageous to have a modular framework for future research

**Comment by SamanthaDawsonBanks** [comment]
good points to include, could be the state of the previous project (not OOP)
- how changing one bit needed to change others
-
