### ISSUE TITLE
Merging Pull Requests

### ISSUE THREAD

**Issue by stevempope** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#24]
https://help.github.com/articles/about-pull-request-merges/

Why do we squash and merge requests, rather than use the default merge or rebase?

Squashing from the article seems to remove our ability to roll back to individual commits.

For example, if 9 out of 11 of my commits to a branch are great and the final two are found later to be faulty, shouldn't we be able to roll back the two and not lose the other 9?

**Comment by SamanthaDawsonBanks** [comment]
looks interesting, the short answer is that it is both the default and what i have been shown how to use it.
i believe there is an issue to do with there being too many commits on a main branch to be of use (this way each commit is a merge)
so i believe the roll back option is to:
undo the merge, then reawaken the branch, branch it as a hotfix, then create a new pull request
as opposed to keeping the merge but rolling back part of it
(all or nothing vs fragments?)

**Comment by stevempope** [comment]
Ok, I am happy with that as an option. My concern was as above, but re awakening branches and re-merging the valid changes seems appropriate.
