### ISSUE TITLE
Acknowledgements

### ISSUE THREAD

**Issue by stevempope** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#248]

**Comment by stevempope** [comment]
Acknowledgements would be anyone who was on the project but who has not written any part of the paper. So I am presuming that would be Charles and Goran, as Charles was on business and not technical and Goran was second reader. Also if any of us end up not producing any text for the paper I presume that is an acknowledgement and not a co author?

**Comment by SaeedMalekshahiUoB** [comment]
The paper submission needs to name peoples who are directly involved with the paper, and contribute to it. This means those who are writing the paper and edit it as well as the main supervisor who has to edit the paper. You are right that Goran and Charles are not part of this paper.
