### ISSUE TITLE
References

### ISSUE THREAD

**Issue by stevempope** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#249]

**Comment by stevempope** [comment]
1st Reference in #238 on PAGE 12 line 20 @ http://www.ce.utexas.edu/prof/kockelman/public_html/TRB15SAVswithDRSinAustin.pdf 
 
Can be found in TRANSPORTATION 45: 1-16 (2016)

DYNAMIC RIDE-SHARING AND FLEET SIZING FOR A SYSTEM OF SHARED 
AUTONOMOUS VEHICLES IN AUSTIN, TEXAS 

 Daniel J. Fagnant 
 The University of Texas at Austin 
 6.9E Cockrell Jr. Hall 
 Austin, TX 78712 
 danfagnant@hotmail.com 

 Kara M. Kockelman
 (Corresponding author)
 E.P. Schoch Professor in Engineering
 Department of Civil, Architectural and Environmental Engineering
 The University of Texas at Austin
 kkockelm@mail.utexas.edu
 Phone: 512-471-0210

**Comment by stevempope** [comment]
2nd Reference #238 

https://arxiv.org/ftp/arxiv/papers/1802/1802.10138.pdf

Real-World Modeling of a Pathfinding Robot Using Robot Operating System (ROS)  
 
Sayyed Jaffar Ali Raza(1), Nitish A. Gupta(2), Nisarg Chitaliya(3), Gita R. Sukthankar(4) 
Department of Electrical Engineering & Computer Engineering University of Central Florida 32816 Orlando, Florida USA 
jaffar@knights.ucf.edu, nitish.gupta@knights.ucf.edu, chitaliya.nisarg4@knights.ucf.edu, gitars@eecs.ucf.edu

**Comment by SamanthaDawsonBanks** [comment]
previous years team project (derived work)
our project (as paper stands alone)
the Git link (info for release etc)
