### ISSUE TITLE
Title of Paper

### ISSUE THREAD

**Issue by stevempope** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#254]

**Comment by stevempope** [comment]
A modular framework for pathfinding research: achieving scalability and cost effectiveness

**Comment by SamanthaDawsonBanks** [comment]
A modular framework for path-finding research: achieving provability, scalability, and cost effectiveness

**Comment by SaeedMalekshahiUoB** [comment]
Good title.

**Comment by HarryWJackson1996** [comment]
good Title, ready to close the issue.

**Comment by RyanShoobert** [comment]
I am happy with the title suggested
