### ISSUE TITLE
Use of nulls in the Herd and Member Objects

### ISSUE THREAD

**Issue by stevempope** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#30]
I would like us as a group to review the Herd and Member classes.

@DavidAveryUoB has quite rightly raised that nulls are used and we should be exploring options that avoid the use of nulls.

I welcome this, however upon review some of the nulls refer to the presence of an object.

Is there a better way of representing these in our code?

**Comment by SamanthaDawsonBanks** [comment]
Yeah revisiting this last night, I think I was just repeating Jim's 'never null' comments.
getLeader() needs to return something and if there is no leader what can we send back?
Optional<T> is a possibility but as per previous discussion #11 that might not be rmi'able.
We could have a dummy member but that would be against 'fail fast, fail hard' as it would appear to be a valid member until it was found to not be... Null looks like the best option, so the jdoc will just need to state that it might be null and to wrap for npe

**Comment by stevempope** [comment]
Ok, thank you for the input. I agree. As long as it is noted that it may return null, then nulls for objects are fine, but isEmpty should be used for lists.
