### ISSUE TITLE
Pathfinding input data type

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#31]
when designing the map I am now looking at the output so, Harry what datatype are you looking to have as the input to the pathfinding?

**Comment by HarryWJackson1996** [comment]
Well the input for the path-finding would be a map, and how they did it last year was use an multi dimensional array of integers. I do not know if this is appropriate for what you are trying to achieve or if it fits into your work?

**Comment by SamanthaDawsonBanks** [comment]
Well part of it is the crossover with #32
As you say they currently use a 2d int array, but we know that their implementation is not very efficient.
Also there implementation used a fixed 800x800 where as ours will be dynamic. 
So it's probably best if we design something new.

**Comment by SamanthaDawsonBanks** [comment]
sorry for the short reply in the other thread I was on my mobile.
i was looking at what a 'map' was and how to store one and that lead to thinking about A* and nodes etc.
so really we have one question in two parts:
what data structure do you want as the input to the pathfinder stuff,
and how flexible will A* be in both 3d environments (as it could matter for the map design to be extensible) and non square grid environments
so if you would have a think of what you want the datatype to be and then i will build it into the map class

**Comment by HarryWJackson1996** [comment]
Hey, from my research to either, use a more efficient algorithm for searching 3d space, or its a problem associated with the heuristics implemented. Using A* to search a 3d space is inefficient because of how it expands on the nodes, but can be helped by using clever heuristics which could be an option. 

In one example of an Optimized A* search algorithm they take in a map in the form:
private final Map<T, Double> heuristic;

So in any case I would need an the input datatype to either be an array of integers or doubles.

**Comment by SamanthaDawsonBanks** [comment]
seams like it might need a bit more research at some point (as the 3d and the n sided grid are similar) but for now...
if this was  the map
![2017-12-19-14 00](https://user-images.githubusercontent.com/25463297/34161138-7d932a8e-e4c7-11e7-868c-dd02d88f5c4b.png)
what would you like the data to look like?

**Comment by HarryWJackson1996** [comment]
too be honest I'm not sure, I thought that map provided would come in some form of an array? For the sake of the project what data type helps you finish the implementation of the map? Because tiles are going to be accessible/inaccessible I'm going to have to work out the distances between the robot and the accessible tiles provided in order to score them.

**Comment by SamanthaDawsonBanks** [comment]
No worries, I just assumed that you might have had a look at it all from your search algorithm research.
So as a primer, and only based on my research over the last week or so (along with some chatting with Steve and Ryan) …
There are two ways of looking at any pathfinding; physically traveling in a direction (north, south, east, west or rotate ϴ° then move X meters), or separately, progressing from one ‘node’ on to the next without caring (or considering) where that node is in real space.
While physical space is seen as a _distance_ between two points nodal space is seen as a _scoring_ of the connections between the nodes.
Physical space has dimensions (x,y even z for 3d) so you often display and even store them as a multi-dimensional array (of Boolean or number values) and with that comes discussions of array copying and data serialising (for communication etc). In addition to this, it means that non-square grids can be complicated to both store and abstract to process. Finally, 3-dimensional space is often seen as layers of 2d worlds and this again complicates the data structure.
If, however, you see all of the ‘spaces’ as nodes that have an undefined number of ‘sides’ or ‘faces’ where you just define that this node (A) is attached to that node (B) then you can store each node as an object that has pointers to the ones that are connected (adjacent) to it.
Once we live in this land, the idea of a 3d ‘grid’ is in fact just a cube that extends a square to also have a pointer to the one in the layer above and another pointer to the one in the layer below. As long as the scoring (heuristics) know how to define one as ‘closer’ than the other all works fine.
With this idea, we very quickly move into Graph theory from discrete mathematics. On graph theory, all places are just nodes that have n connections that cost some ‘effort’ to ‘traverse’ and the “best” route is just the one that costs the lowest effort.
Now the heuristic can be tuned to:
•	Cost X per hop (simple Euclidean or Manhattan distance based)
•	Cost more based on the (historical average) speed that transition takes (so motorways score better than country roads)
•	To impose a ‘penalty’ for certain actions (toll roads, changing trains, or crowded services – so now a “longer” or “slower” route can be preferential over a “shorter” route that requires a toll)
Finally, as a 3d cube is just a node that has 6 ‘edges’ (vertices) it is _mathematically identical_ to a 2d space on a hexagonal grid.
With this in mind the “list of nodes” that a search algorithm considers can be a “collection of nodes with n interconnecting vertices” (in mathematical language) or (in computer science language) a collection of objects (or classes) that have a number of pointers to each other.

Now yes this is rapidly moving into maths and that is not everyone’s strongest or favourite subject. But, we do need to remember that at level 6 (and especially masters) comp-sci _is_ just applied mathematics. So, we may (all) need to just brush up on our maths? (I know I do)

Either way, it does lead us to a suggested data type:
A collection (working idea is an ArrayList) of node objects (that will need to be designed and written for our application).

Comments (from all)???

**Comment by SamanthaDawsonBanks** [comment]
p.s. sorry if that sounded ranty or like I know better, it is just a run down of some research that came out of my investigation into storing maps

**Comment by HarryWJackson1996** [comment]
This doesn't sound ranty but is very helpful. I understand what you mean about real distance vs nodal distance, and being able to extend a square to a cube is extremely useful. I will do some research on graph theory, but from reading what you wrote multiple times a collection could be a good idea, as it provides a lot of useful methods in the collection interface, especially when it comes to having a 'list of nodes'/collection of objects as you have previously stated.

**Comment by SamanthaDawsonBanks** [comment]
discussed and currently going with handing over the map and allowing access to nested vertex

**Comment by SamanthaDawsonBanks** [comment]
Needs more clarification

**Comment by SamanthaDawsonBanks** [comment]
as per #80 the current data type will be a starting vertex (assuming we are starting on map... that might need some thought) with n neighbours that can be got through recursive calls of
this.getOpenNeighbours()

**Comment by SamanthaDawsonBanks** [comment]
#103 
if given a Waypoint [w] and a Map [m]:
m.amalgamatedMap.getVertex(w)
will give you the Vertex [v]
then:
v.edges[] is an array of pointers to its neighbours

so if you call it with you start point as w, you can a* until you find dest D

**Comment by HarryWJackson1996** [comment]
Ok that is amazing! thanks Dave. :)
