### ISSUE TITLE
A* is 2D only?

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#32]
i was working on map grid shapes and that lead to some questions of adjacent nodes, I remember that Harry said that A* was only suitable for 2D maps and that might affect the way I build a map. So Harry can you expand on that point please?

**Comment by HarryWJackson1996** [comment]
Well it searches through the 2d space, but i do not believe it is strictly only for 2d maps. I think the emphasis is on the idea that it works best for 2D spaces but can be implemented in other ways? What did you have in mind? How are you planning to build the map?

**Comment by SamanthaDawsonBanks** [comment]
Map comments in #31 but for search info it could change the data type

**Comment by SamanthaDawsonBanks** [comment]
issue discussion merged into #31
