### ISSUE TITLE
Drive and Sense methods

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#33]
both the driver and the sense methods are currently on my list but I am behind on my work due to not allocating enough (any) time to the data structures. who fancies taking secondary on these methods?

**Comment by RyanShoobert** [comment]
I'm a little behind on my bits as well but I'll be happy to help once I've caught up.

**Comment by SamanthaDawsonBanks** [comment]
that would be great, anyone else got time to spare?

**Comment by stevempope** [comment]
More than happy to help with these bits.

Are you looking for the Arduino side or Java side? Or both?

**Comment by SamanthaDawsonBanks** [comment]
C/Java some and some mostly C but also the facade stuff in J land

**Comment by HarryWJackson1996** [comment]
I don't mind giving it a look as well

**Comment by SamanthaDawsonBanks** [comment]
coolio ty all, sorry for falling behind

**Comment by SamanthaDawsonBanks** [comment]
reopened to link in with MS1

**Comment by SamanthaDawsonBanks** [comment]
info about motors for drive
https://learn.adafruit.com/adafruit-motor-shield-v2-for-arduino/using-stepper-motors

**Comment by SamanthaDawsonBanks** [comment]
info about LiDAR sensor
https://xv11hacking.wikispaces.com/LIDAR+Sensor
and
https://www.impulseadventure.com/elec/robot-lidar-neato-xv11.html

looking a the power specifications for the LiDAR we should really use a closed feedback loop to control PWM on some pins for speed control vs straight voltage.

this is good as it removed another power chain, but does require some more sensing and control code on the sense system...

"The motor can be powered at 3.3V continuous ( ~60mA ) in open loop, which will produce a turn rate of around 240rpm on a clean and recent sensor. Hair and dust can however create friction that will lower the rotation speed.
Using the turn rate information contained in the data, a closed loop control can be implemented, and is recommended."

"Each packet is organized as follows: <start> <index> <speed_L> <speed_H> [Data 0] [Data 1] [Data 2] [Data 3] <checksum_L> <checksum_H>
where: ... ... speed is a two-byte information, little-endian. It represents the speed, in 64th of RPM (aka value in RPM represented in fixed point, with 6 bits used for the decimal part)."

**Comment by SamanthaDawsonBanks** [comment]
Speed should be 180-320 rpm for good data 240 is 3.3v on a 'clean' sensor but does drift

the simplest way to do this is to use AnalogWrite:
https://www.arduino.cc/en/Tutorial/PWM
start it at AnalogWrite(167) //66% of 5v ≈ 3.3v
then on each sense:
if (speed < 220) {inc pwm}
if (speed > 260) {dec pwm}

comments?

**Comment by SamanthaDawsonBanks** [comment]
also remember that there are some flowcharts that define some of these bits in OD/docs/diagrams/flowcharts

**Comment by SamanthaDawsonBanks** [comment]
I have a branch checked-out for the main Arduino Setup and Loop stuff,
I will be assuming the following sigs:
<(ϴ,D)1...(ϴ,D)360>LiDARSense()
<(X,Y)1...(X,Y)360>LiDARToXY(<(ϴ,D)1...(ϴ,D)360>)
(X,Y)Drive(X,Y)
does that work for everyone?

**Comment by stevempope** [comment]
Works for me!

**Comment by SamanthaDawsonBanks** [comment]
re-reading the arduino and LiDAR spec we can't run it straight off the PWM as the arduino can only supply 40mA (peak) 30mA sustained and the LiDAR often needs 60+mA so we will need some for of power controller

**Comment by stevempope** [comment]
Drive is now complete.

**Comment by CFuterman** [comment]
From the meeting that we had on Tuesday, we established that all that was left to close this issue was the sense flow charts that needed updating. Can progress on this front be posted here please.

**Comment by SamanthaDawsonBanks** [comment]
that was a miscommunication;
we have the flowchart, and the logic, but we need to pull the code together from the 4 libraries we are referencing
there is a basic set (from GH/getSurreal/XV_Lidar_Controller) on GH in the LiDAR_Test branch but when i tested it on the hardware Thursday 5th it didn't seem to work right so I will loop Steve in once he is free

**Comment by SamanthaDawsonBanks** [comment]
code planned for tuesday

**Comment by SamanthaDawsonBanks** [comment]
/*
 * Author(s):
 * Name: David Avery
 * Email: d.avery1@uni.brighton.ac.uk
 * Email: David_Michael.Avery@yahoo.co.uk
 * Student Number: 15823926
 * Username: dma23
 *
 * Explanation of Sketch:
 * --Base File Template--
 *
 * Date: 2017
 *
 * Licence of code:
 * Copyright [Authors] David Avery (code), All rights reserved. (Default)
 *
 * References
 *
 */

//------------------------------------Includes-------------------------------------
// any required libraries
#include "Arduino.h"

//-----------------------------------Definitions-----------------------------------
// eg. #define RED 13
// or, #define ON HIGH
#define CONSOLE Serial //usb console
#define CHANNEL Serial1 //board to board TX18 RX19

//------------------------Function prototypes (signatures)-------------------------
// listing signatures assists in debugging!
//eg. int readInt(String prompt); // description & warnings

//--------------------------------Global Variables---------------------------------
// Remember you ONLY have 2k system RAM
// eg. boolean personWaiting = true;

//----------------------------Global Volatile Variables----------------------------
// Volatile variables used by interrupts
// eg. volatile boolean personWaiting = true; // volatile interrupt

//--------------------------------------Setup--------------------------------------
//The setup function is called once at startup of the sketch
// Remember to "Serial.begin(baud);"
// and Initialise I/O pins
// eg. pinMode(RED, OUTPUT);

void setup() {
  // TODO Add your initialisation code here
  CONSOLE.begin(115200);
  CHANNEL.begin(115200); // rate limited 300 baud for stability
}  //End Setup

//-----------------------------Functions / Subroutines-----------------------------

//---------------------------ASM Functions / Subroutines---------------------------

//--------------------------------Interrupt Handlers-------------------------------

//-----------------------------------Loop / Main-----------------------------------
// The loop function is called in an endless loop

void loop() {
  // TODO Add your repeated code here

  if (CHANNEL.available()) {
    CONSOLE.println(CHANNEL.read(),HEX);
    CONSOLE.write(CHANNEL.read()); //if there is something in the channel buffer read it, print it to the console, and loop
  }

  if (CONSOLE.available()) {
    CHANNEL.write(CONSOLE.read()); //if there is something in the console buffer read it, send it to the channel, and loop
  }

}  // End Loop

**Comment by stevempope** [comment]
Update on progress, we have identified how to pick the head of a packet out and reverse the little endian format to pull out the rpm data. We can now apply this logic to the rest of the bytes in the packets and we should be able to pull out some sensor data.

**Comment by SamanthaDawsonBanks** [comment]
Would it be useful if we put together a 'packet' object and/or a return object?

**Comment by stevempope** [comment]
For the moment I am going to work on handing back the pointer to an array, but it's certainly something we should look at when I bring together the final "sense" method

**Comment by stevempope** [comment]
Both Drive and Sense are now complete and ready to have their output turned into Serial-ready content as per #197 Pipe object.
