### ISSUE TITLE
Arrangement of Classes

### ISSUE THREAD

**Issue by stevempope** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#34]
Currently looking at our classes. Most reside in Common, but I am assuming this will change as the roles of the classes become clearer.

My current thinking is that we should have interfaces only in common, everything that relates to drawing a GUI and setting a Destination from the users point of view in ui, leaving the rest of the classes in the pi package.

Does this make sense? Is this the best way to proceed? If so, when? The more code we write, the more will need to refactor later to reflect the package change.

Obviously this only refers to the Java code, as the C++ code is separate and runs on the Arduino.

**Comment by SamanthaDawsonBanks** [comment]
interfaces and maybe datatypes in common but yes pretty much, as for refoactoring late the IDE 'should' be able to update links, but it could invalidate any open branches that also have changes, so i'm thinking of wrapping this #34, #17 and #16 into one "clean up and refactor event" a bit like a code freeze or a milestone
comments??

**Comment by stevempope** [comment]
A milestone sounds very sensible. Perhaps at our first meeting back after the Christmas break we should commit to an "Alpha" milestone in which all of the core working classes are bolted together into a set.

**Comment by SamanthaDawsonBanks** [comment]
#44
