### ISSUE TITLE
Project Logs

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#35]
in order for everyone to work together and for  jobs to be sensible allocated can everyone take some time to update and OD their progress log over the next few days please

**Comment by HarryWJackson1996** [comment]
Will do.

**Comment by stevempope** [comment]
Process Log has been updated.

**Comment by SamanthaDawsonBanks** [comment]
also on the subject of logs (lol) some guidance from the module handbook, module description and grading guidelines...

From the examiners' point of view, the process of research, investigation, thinking, learning and reviewing progress is just as important as the final state of any practical deliverable.

•	clear identification of the problem
•	a clear statement of the project’s aims and objectives
•	background research and contextual investigation as needed
•	awareness of the relevant social, legal, ethical and professional implications
•	identification of the relevant stages of the life cycle undertaken
•	the use of development tools and testing wherever appropriate
•	evaluation of proposed or actual solutions against feasible alternatives
•	critical appraisal covering both product and process.

------------------------------------------------------------

•	both the product and the process elements must be attempted and be of acceptable quality to achieve a pass
•	there must be evidence of appropriate research
•	a very competent evaluation (with hindsight) of the project, its planning and execution can help to compensate for a weak product. The original objectives which is set out for the project, the Planning and investigation Report, may be used as criteria for evaluating the completed project.
•	Weak performance in the evaluation of product and process will result in a grade no higher than B, even if the product is of an exceptional standard.
•	a log which has evidently been manufactured to be handed in rather than having been properly kept will result in a lower grade  

------------------------------------------------------------

•	The Individual Project Log
this is a day-by-day work diary kept by you individually as the project is carried out.
The log is kept mainly for your benefit as it is useful not only as a record of activity, but also as a record of your reflections on the project as it happens, as a notepad when ideas occur and as a general store of working documents which do not need to go into the final report.
The log must be handed at the end of the project; it may be hand written and only one copy per team member is necessary.
