### ISSUE TITLE
Milestone 0

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#39]
***Please ALL read and REPLY***
Regrading (and merging) #34 #17 #16 
there are some structural changes that need to be made to the file system, and they will require that all code be checked-in.
related to this it would be nice if we have a runable (but probably non-working) build some time soon

so I am proposing a milestone build to be done on 12/01/2018

to facilitate that also proposing a prebuild Alpha check-in BEFORE 08/01/2018
so can everyone please commit and push (to their branches) ALL code they have checked-out
to clarify:
all branches will either be merged or shelved on the 8th
no branched created before the 8th will be merged after the 8th (as they will conflict)

[i know we all have a lot of code in progress that is half baked don't worry about quality this is a dev check in]

**Comment by stevempope** [comment]
Understood and agreed. We need to have a working logical model soon.

**Comment by SamanthaDawsonBanks** [comment]
#41 is all of the code I had checked out

**Comment by RyanShoobert** [comment]
I have checked in my current RMI code in #40

**Comment by SamanthaDawsonBanks** [comment]
I believe that the only code outstanding in your branch @HarryWJackson1996 ?

**Comment by SamanthaDawsonBanks** [comment]
Milestone 0 locked
I am starting the refactor so DO NOT pull code until we unlock!

**Comment by SamanthaDawsonBanks** [comment]
#44 please san check and comment

**Comment by SamanthaDawsonBanks** [comment]
merged and moving on to M1
