### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#46]
[Thread for M1 admin, issues should be separate]
***Do we want to set a date? - [one milestone every 4 weeks?]***
M1 - 2018-02-19
M2 - 2018-03-19
M3 - 2018-04-16
FINAL - 2018-05-14
***What is MVT (min viable target) for each?***
***What is final MVP (min viable product)?***

**Comment by RyanShoobert** [comment]
As discussed yesterday, I think the MVP for M1 should be a working solution but where many of the parts don't necessarily work together. 

From there on, I think regular milestones/check-ins will be a good idea (sets 'deadlines' and stops us all sitting on stuff too long like I have at times).

**Comment by HarryWJackson1996** [comment]
I think it is a good idea have the milestones set in place, with the regular meetings to make sure we are actually on track to have a working solution,

**Comment by stevempope** [comment]
I agree with these dates for Milestones. Perhaps we should agree to these dates and make separate issues for each milestone and its spec?

**Comment by SamanthaDawsonBanks** [comment]
The issues system has milestones built in, so I can create the 4 MS and then each issues for that MS gest assigned to it

**Comment by SamanthaDawsonBanks** [comment]
![image](https://user-images.githubusercontent.com/25463297/35562650-ecc7fc86-05ab-11e8-814d-5cc783b9c789.png)
does this look like a working plan?

 
Milestone 1 - MVB / BETA
Due by February 19, 2018
 
Milestone 2 - TBC / RTM
Due by March 19, 2018

Milestone 3 - TBC / GOLD
Due by April 16, 2018

Milestone 4 - TBC / DOCUMENTATION
Due by May 14, 2018

**Comment by stevempope** [comment]
All looks good to me. I would like us to formalise a spec for the first milestone, just so we can reallocate anything we feel that we are missing.

**Comment by SamanthaDawsonBanks** [comment]
yeah each of them need to be defined / confirmed. Currently I have

"Ms1 MVP target is: code; exists (even if stubs), builds (no errors, but warning allowed) signature matches (or it won't build) but methods may not work together (internal testing, or dummy return values)"

comments / adjustments?

**Comment by stevempope** [comment]
Well, we all agreed in our last meeting that we were aiming for a minimum viable product. So we really need to define what that means as checkboxes so we tick them off as done.

As I see it, the MVP should be:

**Hardware**
- Robot body is assembled
- Lidar sensor, Compass and Ultrasound sensors are attached
- Motors and power supply fitted, wheels attached
- Components wired in, Robot is able to power on and all devices check in as ready.

**Herd Behaviour**
- The Pi is able to fire up, create a Herd and then become Leader of that Herd
- Through unit testing, the Herd should be able to accept new members of the Herd. Members can also leave.

**Parallel Processing**
- An instance of our program must be able to invoke remote methods running on another instance of our program on different hardware.
- A good unit test would be send an object and have it be returned, altered in some predetermined way.

**Map Amalgamation**
- In unit testing, a collection of map layers can be amalgamated and returned.

**Pathfinding**
- A generic map can be unit tested and our A* Pathfinding algorithm can successfully choose an approriate path.

**Security**
- The Leader of a Herd should be able to generate a certificate.

**Project Management**
- All process logs must be up to date for 19/02/2018
- All minutes must be up to date and in University style for 19/02/2018
- All links in existing documents must reflect changes made by a refactor of the OneDrive file system.

Please feel free to add anything you think belongs in M1. I think we shouldn't worry about the interaction between the classes unless they are critical for a classes base operation.

I feel if you can unit test and logically prove that a single class works when handed a generic instance of the data it is expecting, then we have a MVP.

**Comment by SamanthaDawsonBanks** [comment]
looks like a good list, i will spin up issues for each of them and assign them out then at they are completed they will link to the milestone

**Comment by CFuterman** [comment]
I have adjusted the milestone dates due to the fact that we now meet on a Thursday rather than a Monday. So the new milestone dates will end the previous Thursday so what the date was.

**Comment by CFuterman** [comment]
Milestone 2 to do list:

- Complete outstanding issues from Milestone 1

- Implementation plan

- Build GUI

- Change from digital pin to I2C for ultrasound sensors

- Unit tests for all classes

- JavaDoc comments for all classes

- Collaborate with Nathan on Quadcopter

- All classes behave as they should - formal proof

- Integration testing

**Comment by SamanthaDawsonBanks** [comment]
Things for MS4
 - Extensibility/Interoperability
 - (G)UI/UX/Usability
 - Communications/RMI
 - Heuristics/Algorithms
 - Mapping/Something
 - Provability/Security
 - Use/Business Case
 - Project Handover Document
 - Scalability Evaluation
 - Implementation Plan
 - Parts List
 - All minutes must be up to date and in University style
 - All process logs must be up to date
 - Final Report Structure

**Comment by stevempope** [comment]
Can this issue be closed now? We have well defined Milestones are working towards finishing.
