### ISSUE TITLE
Final Report Structure

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#47]
any suggestions/comments/additions/etc on the final report structure?

last years final report structure was:
Section 1. The Group Project.
1.1 Introduction to the Project
1.2 The Overall Project Requirements
1.3 The Group Members and Assigned Tasks.

Section 2 Group Research
	2.X [by Member]

Section 3. Group Member Contributions.
	3.X [by Member]

Section 4. Issues Faced Throughout the Project.
	4.X [by Member]

Section 5 Group Conclusion and Reflection.

**Comment by stevempope** [comment]
Sorry for not providing an answer to this before. I feel the report should have section 1 and be a combined effort by all, with 2,3 and 4 a concatenation of our individual work.

As appendicies, we need screens of the GitHub, Facebook Chat and our process logs.

**Comment by SamanthaDawsonBanks** [comment]
no rush on this yet but if anyone has anything to put in the report yet please drop a copy into:
OD\MCOMP_Team\Final Report\
so i can start to compile it

**Comment by SamanthaDawsonBanks** [comment]
separately; can someone take a look at the readme.md {there is probably a template somewhere} and a possible licence (might need to loop in Saeed on that one) for the project

**Comment by SamanthaDawsonBanks** [comment]
anyone?

**Comment by SamanthaDawsonBanks** [comment]
https://choosealicense.com/
https://www.gnu.org/licenses/license-recommendations.en.html
http://www.dcc.ac.uk/resources/how-guides/license-research-data

**Comment by SamanthaDawsonBanks** [comment]
Current report structure (15,000 - 25,000) will be:

Cover Page [David, Charles] (inc. Executive Summery)
Table of Contents [David]
Introduction [All] - 1500
past proj / state of art - 2500
#157 Use/Business Case [Charles, Steve] (states why are we doing this / how are we judging it) ~2000
#158 Provability/Security [Steve, David, Charles] (tees up the we did this to prove it is right) ~2000
#159 Mapping/Persistence [David, Ryan] (carries to know where you are...) ~2000
#160 Heuristics/Optimisation [Harry, David] (mapping is only as good as the PF) ~2000
#161 Communications/RMI [Ryan, David] (slotting it all together) ~2000
#162 (G)UI/UX/Usability [Harry, Charles] (drawing to a close / reflects back to use case) ~2000
#163 Extensibility/Interoperability [Harry, Steve, David, Ryan] (base to build on / looking to future) ~2000
#192 Ethical Considerations [Steve, David, Ryan, Harry] ~2000
Group Conclusion [All] - 3500
**References**
*Appendices*
#154 Project Handover Document [Charles] (start of handover bits)
Suggested Extensions [All] (places this research can go next year / externally)
#155 Separate Reports / Individual Reflective [All] (tees up for prog logs and appendices)
#65 Process Logs [All] (mostly as an include)
#79 Parts List [David]
Code Dump [David] (for doc purposes)
Lexicon of Terms and Names
#173 Readme and License [Charles, David] (as an appendix)

**Comment by SamanthaDawsonBanks** [comment]
we can move it around later but does that look like a logical flow / order?
anything missing?
anything needs to be removed?
anything need editing?
any teams need adjusting?

**Comment by SamanthaDawsonBanks** [comment]
anyone?

**Comment by stevempope** [comment]
I think this looks great, but the ethics should probably come before the handover. It makes logical sense for us to explore the nature of the work we have completed this year and then handing it over to another group/industry.

I am assuming that the hardware we chose for the research bot probably should get a nod in the extensibility section, as a lot of it is modular/off the shelf and provable. It also is a good point for people who want to extend from what we did.

**Comment by SamanthaDawsonBanks** [comment]
Good point, I will edit that on the list

**Comment by SamanthaDawsonBanks** [comment]
there are now 8 more files in the OD/Docs' folder
![image](https://user-images.githubusercontent.com/25463297/39010853-b7fe8232-4407-11e8-8483-2e6726645dae.png)
please put your content in the respective file

also!!!

please do NOT change the formatting or pulling the final file together will be hellish

**Comment by CFuterman** [comment]
I am currently working on my documents in a separate file on my hard drive. Once I have done a bit more, I will put them in to these files. 

Can I make a request that everyone starts working on the topic that they are leading. If you have ideas for other topics you are a secondary to, just note it down as it may be that the lead has written something about it.

**Comment by SamanthaDawsonBanks** [comment]
remember that the sections are being CO-authored so whoever is primary needs to discuss the outline with their mini group.

if we just all do our own sections it will fell like 5 bits bashed together.

**Comment by SamanthaDawsonBanks** [comment]
In that theme a structure that I have found to work well in the past was:

intro
analysis of the problem / task
outline of the proposed solution
design of the solution
discussion / documentation of the solution
reflection on how the implementation went

now for a bigger document we may not want ever sub-section in each chapter (or it will feel fragmented) but it is a starting point

**Comment by SamanthaDawsonBanks** [comment]
c7 being split and removed

**Comment by CFuterman** [comment]
Just a reminder that we decided on during the Skype call yesterday, are we putting our individual reflection at the bottom of our process log?

**Comment by stevempope** [comment]
Final Report Submitted
