### ISSUE TITLE
Hardware day

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#49]
we discussed doing hardware day before we come back from study leave but that could be too short how about to M1?
if so what hardware do we need as it could take time to choose and get delivered?

**Comment by SamanthaDawsonBanks** [comment]
LiDAR sensor - https://www.ebay.co.uk/itm/Neato-Botvac-Lidar-65-70E-75-80-85-D70-D80-D85-Robotic-Vacuum-Cleaner/272912290792?hash=item3f8ad713e8:g:2pMAAOSwcLxYCYv4
battery 12v - https://www.amazon.co.uk/FLOUREON%C2%AE11-1V-2200mAh-Rechargeable-Airplane-Helicopter/dp/B00N79TEBC?pd_rd_wg=gdBAz
battery 9v - 
battery 5v/USB -

**Comment by SamanthaDawsonBanks** [comment]
can someone read up on I2C and the sensors?
https://www.amazon.co.uk/gp/product/B01M0QL1F1/ref=oh_aui_detailpage_o05_s00?ie=UTF8&psc=1
https://www.amazon.co.uk/gp/product/B01KI42UDM/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1
https://www.amazon.co.uk/gp/product/B015R62YHI/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1
https://www.amazon.co.uk/gp/product/B00PIMRJX6/ref=oh_aui_detailpage_o02_s00?ie=UTF8&psc=1
https://www.amazon.co.uk/gp/product/B00R2U8LLG/ref=oh_aui_detailpage_o02_s01?ie=UTF8&psc=1

**Comment by SamanthaDawsonBanks** [comment]
assuming the hardware questions get answered looking at next friday as the build day does that work for people?

**Comment by stevempope** [comment]
As discussed today we need to produce a spec/design diagram to guide us through the build. We have drafted on the whiteboard the design. This will inform our build on Friday. I will produce a more detailed design later today.
![wp_20180215_11_52_39_rich](https://user-images.githubusercontent.com/20892974/36255643-bbdd0a8c-1247-11e8-8d79-e055702775ef.jpg)

**Comment by stevempope** [comment]
This is the top down simplified view of the robot for tomorrows build. Actual implementation will produce a wiring diagram.
<img width="452" alt="robottopdown" src="https://user-images.githubusercontent.com/20892974/36261938-eee8ea34-125d-11e8-8cca-2897d97ae3aa.png">

**Comment by SamanthaDawsonBanks** [comment]
progress so far...

**Comment by SamanthaDawsonBanks** [comment]
![2018-02-16 16 57 00](https://user-images.githubusercontent.com/25463297/36319456-e22cd976-133a-11e8-866f-ae0327dc308a.jpg)

**Comment by SamanthaDawsonBanks** [comment]
![2018-02-16 16 57 19](https://user-images.githubusercontent.com/25463297/36319470-ec0c5a70-133a-11e8-8b9f-6edf1324a43f.jpg)

**Comment by SamanthaDawsonBanks** [comment]
![2018-02-16 16 57 30](https://user-images.githubusercontent.com/25463297/36319478-f44b74dc-133a-11e8-8f80-b1002f5e473f.jpg)

**Comment by stevempope** [comment]
![20180220_115330242_ios](https://user-images.githubusercontent.com/20892974/36504251-ce05efa8-1747-11e8-8e48-dad6d98faa16.jpg)
![20180220_115330345_ios](https://user-images.githubusercontent.com/20892974/36504252-ce2b129c-1747-11e8-95a4-aa00377325ec.jpg)
![20180220_115358386_ios](https://user-images.githubusercontent.com/20892974/36504253-ce4b90ee-1747-11e8-814a-f95b9733c86e.jpg)
![wp_20180220_18_17_52_pro](https://user-images.githubusercontent.com/20892974/36504254-ce6a9e3a-1747-11e8-9496-6675cb83319f.jpg)
![wp_20180220_18_17_57_pro](https://user-images.githubusercontent.com/20892974/36504256-ce8c4c38-1747-11e8-8d77-c845b05040a2.jpg)
![wp_20180220_18_18_03_pro](https://user-images.githubusercontent.com/20892974/36504257-cebf499e-1747-11e8-89e9-474d0dc659e4.jpg)

**Comment by SamanthaDawsonBanks** [comment]
hardware day 2 during easter break? any days work / not work for people?

**Comment by CFuterman** [comment]
We mentioned during the meeting on Tuesday that we were to have another hardware day in the near future. If we could organise one as soon as so that the hardware side to the bot is complete. David, can you put dates that are good for you, as you have all the components. Can everyone else agree on a date that has been given.

**Comment by SamanthaDawsonBanks** [comment]
yeah no probs, dates:
Saturday [7th today] free (all day)
Sunday [8th] free all day
Monday [9th] I am busy but around the house so ppl are welcome to do prelim hardware stuff
Tuesday [10th] I am busy but around the house so people are welcome to come over and do whatever
Wednesday [11th] free (all day)
Thursday [12th] meeting with Saeed (if he is free)
Friday [13th] free after 10:30
Saturday [14th] free (all day)
Sunday [15th] free (all day)

**Comment by SamanthaDawsonBanks** [comment]
as a note my soldering stuff is as uni, as is the lidar kit

**Comment by SamanthaDawsonBanks** [comment]
looking at thursday for build day, so after the meeting

**Comment by stevempope** [comment]
![c1b3445b-11e8-48fe-be49-fb819fa43133](https://user-images.githubusercontent.com/20892974/38765168-ad5fc5b8-3fb4-11e8-92d6-694ccdc06630.jpeg)
![2c433e72-4221-4118-a387-9205b9e52660](https://user-images.githubusercontent.com/20892974/38765169-ad8ad690-3fb4-11e8-9668-fc76883c377a.jpeg)
![6758e31c-edf8-448d-b165-92440905906c](https://user-images.githubusercontent.com/20892974/38765170-ada6a3b6-3fb4-11e8-970a-a7ce55ba4301.jpeg)

**Comment by stevempope** [comment]
So the power supplies are now fitted and the ultrasounds are ready to be rotated and wired up to the power supply. The remaining fitting to to be done is the lidar the ultra sounds and the compass module. The us have mounts and just need rotating, the lidar needs adapting or a smalller thread and to be mounted with the dimple facing forward and the the compass is arriving tomorrow.

**Comment by stevempope** [comment]
The wheels are arriving soon too

**Comment by SamanthaDawsonBanks** [comment]
Both options for wheels are here now, so I will have a look at which fit better
