### ISSUE TITLE
Change Arduino Drive Sig from (x,y) to (ϴ,D)

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#51]
Currently the Drive method is prototyped as taking an absolute WP (X,Y) and then calculating an angle ϴ and distance.
comments on changing its sig to (ϴ,D)?

WP (X,Y) is common on all platforms
"Thing" (ϴ,D) is less processing on the 'duino?

**Comment by stevempope** [comment]
Perhaps we need to review the trigonometry as a group. Moving the angle calculation high in the abstraction layers reduces our modularity.

**Comment by SamanthaDawsonBanks** [comment]
Yeah going over the trig could be useful it took me some time to get back up to speed.
In the meantime OD/research/David/Trig_Cheat_Sheet.pdf
For some basics

**Comment by SamanthaDawsonBanks** [comment]
mostly discussed and decided to leave at WP(x,y) but there is a CS vs BS discussion to document
