### ISSUE TITLE
Go backwards?

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#52]
we have rotate and forwards do we want reverse?

we can turn in place so no real need.
But it could be useful in some use cases?

**Comment by stevempope** [comment]
Whilst it isn't an issue for us and our research bot, its probably worth thinking about. There are several arguments, but the movement is modular. I think we shouldn't add it for our bot as it can rotate in its own length, perhaps we should instead talk about reversing as an additional feature for certain form factors. That might extend nicely into the modular/use case argument we are trying to make.

**Comment by SamanthaDawsonBanks** [comment]
Again discussed and decided to be CS vs case study, decided to leave as 'no reverse' but leave space in API
