### ISSUE TITLE
Meeting Minutes

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#53]
I saw that there were two different formats / styles for our minutes. I have dropped two examples of typical minutes that are used in the UoB (school board and course board) they might be useful for style tips, of if you just want to see what we chat about.

OD\MCOMP_Team\example_minutes

**Comment by stevempope** [comment]
I think it would be good to format it similar to official University style. Thanks for this Dave.

**Comment by SamanthaDawsonBanks** [comment]
crossed in #66
