### ISSUE TITLE
Robot body assembled

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#54]

**Comment by SamanthaDawsonBanks** [comment]
who else wants in on this? assign yourself if you are interested in getting burnt by a soldering iron

**Comment by HarryWJackson1996** [comment]
sounds like fun. However not too familiar with hardware, rather the assembly of it. But happy to join in.

**Comment by stevempope** [comment]
If everyone has some time this Friday (16th February) We should assemble what parts we have so far.

**Comment by RyanShoobert** [comment]
I'm free on Friday and am happy to come along
