### ISSUE TITLE
Lidar sensor, Compass and Ultrasound sensors attached

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#55]

**Comment by SamanthaDawsonBanks** [comment]
see sensors help request in #49

**Comment by SamanthaDawsonBanks** [comment]
compass / sensor has been soldered, so is plugin ready, ultrasound sensors are attached to their brackets just need attaching to the chassis

**Comment by stevempope** [comment]
Everything for this is issue apart from attaching the LiDAR sensor is now complete.

**Comment by SamanthaDawsonBanks** [comment]
and compass, but that is just i2c pretty much straight on to the board

**Comment by SamanthaDawsonBanks** [comment]
planned for #49

**Comment by SamanthaDawsonBanks** [comment]
lidar is now "fitted" US mounts have arrived compass looking like MS5

**Comment by SamanthaDawsonBanks** [comment]
scheduled for Wednesday meetup (except compass)
