### ISSUE TITLE
Motors and power supply fitted, wheels attached

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#56]

**Comment by SamanthaDawsonBanks** [comment]
can some one look into batteries plz as per request in #49

**Comment by SamanthaDawsonBanks** [comment]
Adjusted MS to M2 awaiting 12v battery

**Comment by stevempope** [comment]
I have wired in the motors to the motor shield.

The wires that come with 12v power supply do not fit. They are too wide to fit in the motor shield and are massively over provisioned for the PSU we are using. We need to find a AWG of 16 or higher (thinner) as the current 12 is too thick.

PSU's have arrived.

**Comment by SamanthaDawsonBanks** [comment]
planned for #49

**Comment by CFuterman** [comment]
I understand that the wheels are yet to be attached, how is the rest of this coming along?

**Comment by SamanthaDawsonBanks** [comment]
Wheels: we need to pick the wheels then i need to order them, as for fitting they are push fit on the the motors so fitting should be a 2 minute job
power: battery is charged (but at uni as I don't have a charger) and I need to make up a cable with the right ends

**Comment by SamanthaDawsonBanks** [comment]
https://www.amazon.co.uk/Shepherd-Hardware-9610-Semi-Pneumatic-Replacement/dp/B000N6BR3A/
https://www.amazon.co.uk/UNIVERSAL-6-REPLACEMENT-LAWNMOWER-WHEEL/dp/B0018U4408/

**Comment by stevempope** [comment]
Just awaiting the wheels arriving and being fitted then we can close this issue

**Comment by SamanthaDawsonBanks** [comment]
eta on wheels = Monday 16th

**Comment by SamanthaDawsonBanks** [comment]
alt wheels arrived just need drilling and fitting

**Comment by SamanthaDawsonBanks** [comment]
issues with the wheels (they keep falling off...) but otherwise all good?

**Comment by SamanthaDawsonBanks** [comment]
scheduled for Wednesday meetup
