### ISSUE TITLE
Components wired in, Robot able to power on and all devices check in as ready

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#57]

**Comment by SamanthaDawsonBanks** [comment]
awaiting power supply (motor battery and LiDAR battery) eta 3 days

**Comment by SamanthaDawsonBanks** [comment]
power stuff is here fitting soon

**Comment by SamanthaDawsonBanks** [comment]
planned for #49

**Comment by CFuterman** [comment]
From Tuesday's meeting, we saw the bot being powered. How is the fitting of all components coming along? Can we have an eta for each of the outstanding components please.

**Comment by SamanthaDawsonBanks** [comment]
Fitted: pi, ard, motors, ultrasound (usound needs some more work)
Testing: LiDAR (only needs 4 bolts to mount)
Waiting: wheels, battery, power cable

**Comment by stevempope** [comment]
Remaining tasks associated with this issue, attach LiDAR, plug teensy arduinos into usb power, wire teensy Arduino into mega digital pins, usb between mega and Pi, usb power from battery to Pi, attach wheels.

These will be folded into a final Hardware day when the robot wheels arrive.

**Comment by SamanthaDawsonBanks** [comment]
other then MPU (compass) done(ish)
