### ISSUE TITLE
The Pi is able to fire up, create a Herd and then become Leader of that Herd

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#58]

**Comment by SamanthaDawsonBanks** [comment]
Raspbian installed (it comes with JRE) need some bits from WiFi etc

**Comment by SamanthaDawsonBanks** [comment]
pi arduino info
https://wiki.debian.org/Arduino

**Comment by SamanthaDawsonBanks** [comment]
pi is setup and has both arduino and eclipse installed (I will setup the 2nd SD Card) [and probably a backup one]
over to java land...

**Comment by SamanthaDawsonBanks** [comment]
I have the test hardware with me most days so we can do some runtime tests next time we meet up?

**Comment by stevempope** [comment]
@DavidAveryUoB has completed this.
