### ISSUE TITLE
RMI setup

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#60]
An instance of our program must be able to invoke remote methods running on another instance of our program on different hardware.

**Comment by stevempope** [comment]
Are we able to use this now @RyanShoobertUoB?

**Comment by RyanShoobert** [comment]
Setup code is currently done but some work is still needed on intrgerating this with the main method.

**Comment by RyanShoobert** [comment]
Leader and Member code merged but still in development.

**Comment by stevempope** [comment]
Echoing @RyanShoobertUoB the member and Leader are in development but there needs to be a bit more work done to incorporate the RMI elements.

**Comment by SamanthaDawsonBanks** [comment]
Leader to Member RMI is now setup (but only one method [drive] is currently being RMIed)
I still need to factor out some bits (types and interfaces) - to be discussed on s4b at some point
[mostly just if a collection is a collection of classes or interfaces (it makes more sense with an example) but also some who is told what stuff]

think: is herd.herdDrivers a collections of members(who happen to have the ability DRIVER) or of objects that specifically implement the driverable interface... and then what list do you iterate through, and where do you add members to etc

**Comment by SamanthaDawsonBanks** [comment]
fixed? in #152

**Comment by SamanthaDawsonBanks** [comment]
closing as merged, there is still work to do but: The steps we take don’t need to be big; they just need to take us in the right direction
