### ISSUE TITLE
Map Amalgamation

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#62]
In unit testing, a collection of map layers can be amalgamated and returned.

**Comment by SamanthaDawsonBanks** [comment]
as per #13 #31 and #32 there are some question as to the map object @HarryWJackson1996 I will grab you for coffee at some point to discuss it.

**Comment by HarryWJackson1996** [comment]
Yeah no problem, let me know when you are free to discuss the map object.

**Comment by SamanthaDawsonBanks** [comment]
current half baked map was PR'ed with #81 

I am planning to place this **on hold**

if anyone needs any methods (such as data output) please post the signature here and I will  hotfix them in.

**Comment by SamanthaDawsonBanks** [comment]
"working" map is in #103 for consideration
