### ISSUE TITLE
A* Pathfinding

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#63]
A generic map can be unit tested and our A* Pathfinding algorithm can successfully choose an approriate path.

**Comment by HarryWJackson1996** [comment]
As mentioned in the previous meeting, I was struggling with the implementation of the A* without a testable map. Now the map has been finished it will should be relatively straightfoward to implement the A*. However other coursework deadlines are fast approaching. After the 02.03 The deadline would have passed and I can completely focus on finishing the algorithm
