### ISSUE TITLE
The Leader of a Herd should be able to generate a certificate.

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#64]

**Comment by SamanthaDawsonBanks** [comment]
https://stackoverflow.com/questions/26830617/java-running-bash-commands

**Comment by stevempope** [comment]
The plan is to use the inbuilt OS (Rasbian) to generate a Self-Signed Certificate. The SSL cert will then be imported into the Java keystore and used to encrypt any traffic sent from the leader object.

**Comment by stevempope** [comment]
Closed as merged
