### ISSUE TITLE
All minutes must be up to date and in University style

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#66]
All minutes must be up to date and in University style for 19/02/2018

**Comment by CFuterman** [comment]
I will have the minutes from this week updated by tomorrow morning. I'll sort out the university style by next week's meeting.

**Comment by stevempope** [comment]
How are we for minutes? Our meetings have changed purpose from the "planning" section, as we are coding more. Do we still need to produce minutes where the agenda is "keep coding" or "reach milestones"?

**Comment by RyanShoobert** [comment]
Sounds like a sensible idea @stevempope as much of the coding phase has been self documenting on git. What does everyone else think?
