### ISSUE TITLE
All links in existing documents must work

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#67]
All links in existing documents must reflect changes made by a refactor of the OneDrive file system.

**Comment by stevempope** [comment]
This will tie into our refactoring of the OD folder. @DavidAveryUoB and @RyanShoobertUoB would you please put a changelog of what gets moved in here so that we can check them off in our documents?

Suggested format:

Old folder/filepath -> New folder/filepath

**Comment by RyanShoobert** [comment]
Agreed, this will tie in with #48 and a file documenting these changes is a good idea. 

I will have a chat with @DavidAveryUoB and we'll get this refactor done.

**Comment by RyanShoobert** [comment]
All files that have been referenced are still accessible with the provided links.
