### ISSUE TITLE
Heuristic Planning

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#68]
what and how to calc

**Comment by stevempope** [comment]
Perhaps we could use cascading rules and assign a cumulative score at each junction.

An example would be we hand in a grid location and the first rule is "does it get me closer to destination" Which is applied a score if it does, say 5.

That same location is tested again against other rules and the score from each rule is added to the total value, which becomes the score. Obviously in a large search space rules should be kept to a minimum, but it does allow us to have a "compound hueristic".

**Comment by SamanthaDawsonBanks** [comment]
sounds reasonable, the first I would suggest would be that turn > drive with regards to cost. that way we can reduce the number of turns

**Comment by SamanthaDawsonBanks** [comment]
crosses with #75

**Comment by HarryWJackson1996** [comment]
The  stupid heuristics have been programmed and are ready to be used. Currently working on the the straight line vs  turn heuristic.
