### ISSUE TITLE
Number of Vertex Edges

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#69]
so currently the number of vertex edges is equal to the 'sides' of the grid (so squares have 4).
This allows for 'side to side' navigation but not diagonal.
we could make edges = 2*sides (so square has 8, 4 cardinal and 4 diagonal)

pros:
better pathfinding

cons:
needs some adjusting to the heuristics (diagonal is equal to: √(1+1) not simply 1)

comments?

**Comment by HarryWJackson1996** [comment]
I think as of milestone 1, we should only consider the edges of each square, so side to side navigation. Yes diagonal movement allows for better pathfinding, but I feel the focus should be on getting simple navigation working well before extending into 8 directions.

**Comment by stevempope** [comment]
If we are making a 4 sided object behave as if it has 8, then why not have an 8 sided object, solving the issues with moving diagonally in a square based grid anyway (namely, how can we be sure that the robot  will fit through that gap)?

This isn't a Milestone 1 issue as such, as Harry says, but we are putting issues up for all timescales in the project. Maybe this is a M2 issue, so we have working pathfinding in M1 and advanced in M2?

**Comment by stevempope** [comment]
I think my first part came across a little harsh. Squares aligned in a grid have edges that touch the neighbouring square by exactly the squares width and height. A square in a diagonal direction only touches the very corner of the square. If the north and east square is blocked and the northeast not, our pathfinding may assume a valid route where there is not one, but also in reverse assume a route that is perfectly traversable is not.

**Comment by SamanthaDawsonBanks** [comment]
Question moved to M2 - going with Edges = Sides

**Comment by SamanthaDawsonBanks** [comment]
closed as answered
