### ISSUE TITLE
Refactor Maps Region > Chunk > Vertex to be isomorphic

### ISSUE THREAD

**Issue by SamanthaDawsonBanks** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#72]
when describing these abstractly they are all 'things' that have pointers to their 'neighbours' and hold collections of 'things'
so they are isomorphic and could be refactored to reduce use a runtime specific implementation.

but this is bigger/less important than M1 hence H2

[mostly just a comment so I remember to do (or farm out) this]

**Comment by stevempope** [comment]
You are right. The classes have identical method sigs. The only advantage I can see is they are easier to explain. Really though a region contains n number regions to fill the world and so on.

**Comment by SamanthaDawsonBanks** [comment]
and all of the internal math is just gridsize^[how nested this layer is] so:
vert = ^0
chunk = ^1
region = ^2
and griddedmap = ^3

**Comment by stevempope** [comment]
Should make this a Milestone 5 objective? I believe we are happy with the changes in #190
