### ISSUE TITLE
Getting the IP address of a Member

### ISSUE THREAD

**Issue by stevempope** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#73]
We have discussed the network topology today.

One of the questions that arose was how we would extract the IP info of a client.

I am not sure what stage we need to extract the IP address but we talked about several models of access.

I have two methods. One polls the "active" network port. The method is lightweight but doesn't guarantee which network adapter responds.

The second method returns from every available network adapter, allowing us to further check the MAC address etc.

The Raspberry Pi has more than one network interface (Ethernet and wifi). The question is do we want to poll the list of available adapters every time or do we disable the wired port to guarantee that we get the right adapter?

**Comment by stevempope** [comment]
Some reference from StackOverflow

https://stackoverflow.com/questions/9481865/getting-the-ip-address-of-the-current-machine-using-java

**Comment by stevempope** [comment]
Apologies if my question was a little vague, it was getting late yesterday.

We need to extract the IP of the leader when it is promoted, so that members of the Herd can in the future be informed of their "gateway" address. We agreed that we would use the leader as the Access Point for the network, using DHCP to hand out IP addresses. The question then is how we handle the network adapters on the Pi.

**Comment by stevempope** [comment]
Here is the oracle docs page for Inet address

https://docs.oracle.com/javase/7/docs/api/java/net/InetAddress.html

**Comment by stevempope** [comment]
NetworkInterface is the alternative option for extracting network information

https://docs.oracle.com/javase/7/docs/api/java/net/NetworkInterface.html

**Comment by SamanthaDawsonBanks** [comment]
Each interface should be named, so we can probably request info from wlan0 directly but depends on the api.
Disabling the rest could be a bit random as there will be loop back and bluetooth as well, disabling all but wifi could cripple other functions

**Comment by stevempope** [comment]
I am leaning towards the Network Interfaces option. The Inet address option only hands us an IP address and also forces us to make assumptions about the number of available interfaces etc. If there aren't any objections I will write some code for the Network Interfaces (I already had a Inet address one) and generate a pull request.

**Comment by stevempope** [comment]
So I have been reviewing the methods and have changed my mind totally. I have managed to get the InetAddress class to produce a list of all IPv4 and 6 addresses from the host client. There won't be any need to disable or assume anything. We can now simply use logic in the leader class to determine what details it will publish.

I will leave this issue open until I add the code and produce a pull request.

**Comment by stevempope** [comment]
Closing as I have made a pull request
