### ISSUE TITLE
Role of the Leader: Class or Process?

### ISSUE THREAD

**Issue by stevempope** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#74]
We need to discuss how a leader works as part of a Herd.

Currently leader is a role that a member takes.

As the job of a leader is to distribute information about the Herd to other members, as well as hand chunks of map to processors to handle, should it be run in a separate Java process, or as part of the Herd process.

A key advantage of having the Leader in a separate process is that interaction between the member and leader on the same robot is handled as if it were any of the other robots.

Open to opinion on the pros and cons, so please discuss.

**Comment by SamanthaDawsonBanks** [comment]
current working plan is separate <processes>
so that the leader <-> member relation is always serviced by RMI even when on one bot?

**Comment by SamanthaDawsonBanks** [comment]
crosses with #94

**Comment by SamanthaDawsonBanks** [comment]
decide on process,
closing
