### ISSUE TITLE
Vertex: Blocked, Unblocked and null

### ISSUE THREAD

**Issue by HarryWJackson1996** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#80]
For clarification, if an edge points to null then there is no data associated with that connected Vertex? The vertex is in one of three states, Blocked, Unblocked and null.  If it is null the bot can still traverse it.

**Comment by SamanthaDawsonBanks** [comment]
Yeah, I'm still trying to work out the best way to model this bit (hence #13 and #31).
but in general:
a map starts out 'blank' so all vertices (vertexes) are just pointers to null [to save storage space or the map data structure get big very fast]
when a data point is added that point is set to "blocked" [a final static instance of vertex that can be check for using .equals()]
AND all vertices that point into that blocked vertex need to be created (blank) and have their pointers set to also point to blocked
![2018-02-18-15 14](https://user-images.githubusercontent.com/25463297/36353698-8edd4610-14c1-11e8-8f04-2099ca572058.png)
this should then give us vertices in three states:
null = nothing is known about this vertex or its neighbours = can assume 'empty'
exists = this vertex is clear but one [or more] of its neighbours is blocked
blocked = this vertex is blocked and cannot be driven through

Data on Grid
![2018-02-18-15 23](https://user-images.githubusercontent.com/25463297/36353710-9682195e-14c1-11e8-8bf3-8bed8f90ad1b.png)

Red = blocked
![2018-02-18-15 24](https://user-images.githubusercontent.com/25463297/36353720-b4267176-14c1-11e8-8d22-174e9d535159.png)

Green = exists but neighbour blocked
![2018-02-18-15 26](https://user-images.githubusercontent.com/25463297/36353730-c619da80-14c1-11e8-8940-ae44d8d68be0.png)

Orange = null
![2018-02-18-15 27](https://user-images.githubusercontent.com/25463297/36353735-cd60efae-14c1-11e8-874b-bddc4a08360c.png)

**Comment by SamanthaDawsonBanks** [comment]
if we assume:
0,0 in the bottom left corner;
starting loc of (0,5) [the gap on the left side of the map]
destination of (14,7) [the top block of the gap on the right]

we see that some of the node that will be searched will exist and some will be null even in a 'fully' mapped room

equally if the destination is "off in the cloud of null-space"  say at (17,1) [bottom right corner of the new extended map]
![2018-02-18-15 46](https://user-images.githubusercontent.com/25463297/36353848-839f2064-14c3-11e8-94ea-fd8fbf1d7b65.png)
the pathing will map a 'known' route through the 'room' and then just "straight-line through the nulls" to the destination

**Comment by SamanthaDawsonBanks** [comment]
so.... it's a little like a minesweeper map
![image](https://user-images.githubusercontent.com/25463297/36353897-7b46f026-14c4-11e8-9550-b43ce586b0ca.png)
[http://minesweeperonline.com/#]

**Comment by HarryWJackson1996** [comment]
So from that i can understand that if an object exists in a tile, that tile is set to blocked. All the pointers around it from the other tiles are set to blocked. However if no object exists with in a tile and its pointer is not set to blocked then its null (or if its diagonal of a blocked tile).

**Comment by HarryWJackson1996** [comment]
However is the grid overlay just preset to the whole search space or only on the currently known space? Because in the above example that is when the whole map is known.
![blocked-unblocked-null](https://user-images.githubusercontent.com/32718213/36357943-bc964e8a-14fd-11e8-9807-a5937e6bc345.png)
![blocked-unblocked-null-nogrid](https://user-images.githubusercontent.com/32718213/36357944-bcb02fb2-14fd-11e8-8618-d503151baf5e.png)

**Comment by HarryWJackson1996** [comment]
Because given that was the first snapshot. Based on the first diagram would all other white tiles be considered null until the robot has moved, re-scanned from its new position and updated the map with the new relevant objects?

**Comment by HarryWJackson1996** [comment]
I apologize for all the questions, but completely understanding the map and the theory applied to it helps me when considering path optimization.

**Comment by SamanthaDawsonBanks** [comment]
yeah no worries mate, questions are good they show that we are all working as a team :)
to answer: the grid always 'exists' as there is a 64x64 array of storage that can hold vertices, but the array is uninitialised so they all point to null until something is written to that space

![nullmap](https://user-images.githubusercontent.com/25463297/36369906-e99a2350-1554-11e8-834a-617cb1ebe42c.png)

**Comment by HarryWJackson1996** [comment]
Yeah that image is what i would of expected to see and really helps when implementing path optimization! :)

**Comment by SamanthaDawsonBanks** [comment]
closed, as answered
