### ISSUE TITLE
Executive Summaries

### ISSUE THREAD

**Issue by CFuterman** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#82]
In professional and research projects, often you must be able to explain your work in non technical speech i.e, in a viva like we have done. I think it may be useful to be able to write down just a short summary in this way just for some practice. It will also help me to get a better understanding as someone who isn't as technical on what it is that your research will achieve. 

I have made a folder on the OneDrive. Research -> Executive Summaries. Just keep it short and sweet, 250 words tops.

**Comment by stevempope** [comment]
All done. Really good idea for developing our skills beyond Computer Science.

**Comment by SamanthaDawsonBanks** [comment]
Uploaded, yeah nice one mate its good practise to see the connection between research and business application.

**Comment by CFuterman** [comment]
I'm working tonight, so tomorrow I will look over what you guys have got and give my feedback at our meeting on Thursday.
