### ISSUE TITLE
Creating the Drive Method

### ISSUE THREAD

**Issue by stevempope** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#83]
Hi all,

As in #51, Dave has done a lot of research regarding the required trigonometry to allow us to use the Arduino to calculate the number of pulses to the stepper motor (allowing us to turn and move the robot). I have volunteered to create the drive method, but I want to check that I have my circle theory right.

Please see below the Whiteboard photos and finalised pseudo maths/code for the drive method. The interrupt code is missing currently but I need to look more into hardware interrupts as I have not given them much thought since the end of CI116.
![20180221_095002737_ios](https://user-images.githubusercontent.com/20892974/36504592-f22738dc-1748-11e8-970b-097554a256eb.jpg)

![wp_20180221_09_38_05_rich](https://user-images.githubusercontent.com/20892974/36504595-f6fc0b62-1748-11e8-91a9-76c62a01fc7c.jpg)

So the general idea is that we are handed a Waypoint (x,y).

We know the current position of the robot, so we can divide the y value of the current position with the y value of the final position (therefore the height of the opposite in Pythagoras) and multiply it by TAN to the power negative 1 to give us our turn angle theta.

The distance travelled is the root of the difference between the two x's squared added to the difference between the two y's squared. We can use some different trig for this if needed.

Now we have the turn and distance, we can calculate what that means for the robot.

There are two circles to consider. First, the robot body must move by the turn angle theta. Second, the wheels must rotate in opposite directions by an amount to make the robot turn the required distance.

To work out the distance the robot needs to turn by to meet angle theta, we divide the angle theta by 360 degrees, and multiply that value by the standard circumference calculation, 2 x pi x radius (of the robot body).

We now have a target amount of distance to be covered by the wheels, which brings us to the second circle.

In order to work out how many pulses of the motors make that distance, we need know how big the wheels are. A pulse of 1.8 degrees on bigger wheels generates more travelled distance.

Dividing 1.8 by 360 degrees and multiplying this value by the standard circumference calculation 2 x pi x radius (of attached wheel) gives us the amount of distance that is covered by a single pulse.

Dividing the distance the body is required to turn by the distance covered in a single pulse gives us the number of pulses required to turn by the angle theta.

Dividing the distance by the distance covered by a single pulse gives us the number of motor pulses required to move to the destination.

To the apply the drive method without the interrupt, we pulse the right motor by the number of pulses required to turn the right wheels while pulsing the left motors by the negative equivalent of that value, giving us our turn. We then pulse both at the same time to move forward by the required amount.

![wp_20180221_20_47_53_rich](https://user-images.githubusercontent.com/20892974/36504949-0140071c-174a-11e8-88ee-412f7bd92ffa.jpg)

I hope this all makes sense, please check me or correct me if I am wrong. (I often am!)

**Comment by HarryWJackson1996** [comment]
I have begun implementing the maths for the drive functionality based on the the diagrams and images provided. From our last meeting if i'm correct, angles needed to be in degrees? This is because the math library returns the results in terms of radians and therefore will need to be converted. Today I'm testing the code to make sure it actually works from a mock up scenario, as i'm not 100% sure the phi implementation I have is completely correct.

**Comment by SamanthaDawsonBanks** [comment]
reference math is in #20

**Comment by SamanthaDawsonBanks** [comment]
cross of #33
