### ISSUE TITLE
Complete outstanding issues from MS1

### ISSUE THREAD

**Issue by CFuterman** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#84]

**Comment by stevempope** [comment]
Current outstanding issues are #33, #55, #57, #58, #59, #60, #61, #62, #63, #68 and #74 although I believe that we are close to completion on most.

**Comment by CFuterman** [comment]
As this is the case, is it realistic to set this as a target for next week's meeting aim? This way we can use this as a start of ticking off things for M2, which as a reminder, is March 15th.

**Comment by CFuterman** [comment]
Anything that can use assistance of that you know I would be assistance of, please let me know. Thanks!

**Comment by SamanthaDawsonBanks** [comment]
next Thursday is a good goal but most of us have 1-2 other bits of CW due in the next 7 days.
i'm hoping to get my project bits to a point where they are not delaying anyone else then, I will be probably focus on other CW for a week before returning to project stuff

**Comment by HarryWJackson1996** [comment]
Im with David I try and get my bits up to date, but I have two impending deadline approaching.

**Comment by SamanthaDawsonBanks** [comment]
#62 done

**Comment by SamanthaDawsonBanks** [comment]
majority of the issues have either been completed or kicked down to ms2
