### ISSUE TITLE
Build GUI

### ISSUE THREAD

**Issue by CFuterman** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#86]

**Comment by stevempope** [comment]
I was thinking for a GUI design, we should have a "live" view of what each lidar sensor is seeing, plus maybe some information about herd members and abilities. Any thoughts to chuck in?

**Comment by HarryWJackson1996** [comment]
I think it is a great idea to have a live view of what each member is viewing. Showing some information about each member is also quite useful. By doing so can closely monitor each individual herd member. With regards to that idea, have you thought about the implementation?

**Comment by CFuterman** [comment]
That's a good idea, just think about from the user's point of view that it must be clear which LiDAR sensor they are seeing the information from otherwise it will be easy to get confused.

**Comment by stevempope** [comment]
Yeah, so I was thinking have a robot image in a frame, with the raw sensor output on screen. We have existing code to map lidar output to screen. The "grid" would be applied at the software level for pathfinding. I need to speak to @DavidAveryUoB but we could overlay a grid as another view?

**Comment by SamanthaDawsonBanks** [comment]
with the planned map structure we have access to latest (well all ever) LiDAR reads and the gridded map so it should be easy enough to give a suitable interface

**Comment by SamanthaDawsonBanks** [comment]
The LiDAR will be in the form of collection of WPs and the total map is already gridded

**Comment by SamanthaDawsonBanks** [comment]
![image](https://user-images.githubusercontent.com/25463297/36593820-46d0cc22-1893-11e8-8785-4c42044baa60.png)
and 
![image](https://user-images.githubusercontent.com/25463297/36593827-4b82665e-1893-11e8-8b8b-7bbb2e1b7b5f.png)

**Comment by SamanthaDawsonBanks** [comment]
also it would be nice if we can pretty it up a bit maybe like hud at the bottom of the Saeed and Alan robot video?
https://www.youtube.com/watch?v=ATLUgaOlUpo

**Comment by SamanthaDawsonBanks** [comment]
this needs to consider #170 the View will be held by a member (of type Notifiable) so it will have access to a locally synced Herd data structure (in Member.localHerdData) that will then contain:
Map,
Destination,
Path,
Herd Members,
Leader,

so while testing can use fixed input data, the final should make use of variables and datatypes

**Comment by RyanShoobert** [comment]
The toArrayList() method has now been implemented for drawing the map on screen. Is there any chance of a PR for some of the latest GUI bits as I know you've been working on it.
