### ISSUE TITLE
Change from digital pin to I2C for ultrasound sensors

### ISSUE THREAD

**Issue by CFuterman** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#87]

**Comment by SamanthaDawsonBanks** [comment]
i2c US sensors seem to be £30+ each
one option is to embed a atTiny as per:
https://gist.github.com/ajfisher/1d57c5f845c376f04fbb
https://www.adafruit.com/product/1501

or to stay with the digital pin design?

comments?

**Comment by CFuterman** [comment]
Looking at our requirements and that we're working on a budget. The change would take our project over budget. It's easy to want to upgrade the bot, but in this case it would help to fulfill our requirement by sticking with the original digital pin design.

**Comment by SamanthaDawsonBanks** [comment]
reopening as there is some code needed

**Comment by stevempope** [comment]
@RyanShoobertUoB has completed most of the work in this area. We will be mounting the sensors on 13/04/2018 all going well.

**Comment by stevempope** [comment]
This issue can now be closed as we have working code using digital pins attached to teensy Arduino that will light a digital pin on the mega board when the trigger distance is reached.
