### ISSUE TITLE
Unit Tests for all classes

### ISSUE THREAD

**Issue by CFuterman** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#88]

**Comment by SamanthaDawsonBanks** [comment]
C datatypes unit test done

**Comment by stevempope** [comment]
Herd Unit tests are done in their current guise. The members tests were fine but there is some refactoring to come in this area so I can't mark it as done yet.

**Comment by stevempope** [comment]
Unit tests for a Waypoint and C Path were created by @DavidAveryUoB  and I have created tests for drive as part of #150
