### ISSUE TITLE
JavaDoc comments for all classes

### ISSUE THREAD

**Issue by CFuterman** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#89]

**Comment by SamanthaDawsonBanks** [comment]
I'm terrible at documentation ("bad Dave no doc = bad coder") if anyone is available and looking for somersaulting to do can they give me a hand / some pointers

**Comment by CFuterman** [comment]
I'm happy to help give a hand at the documentation. On the next meeting, I am happy to stay a bit longer in order to give a hand in documentation, whether it is just to template some things for you to fill in or sit with you and do it with you. Let me know.

**Comment by SamanthaDawsonBanks** [comment]
duplicate of #17
