### ISSUE TITLE
Publish Open API - Collaborate with Nathan on Quadcopter

### ISSUE THREAD

**Issue by CFuterman** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#90]

**Comment by SamanthaDawsonBanks** [comment]
current plan is to use some form of Bluetooth beacon for the QC (quadcopter) to be able to locate us (Nathan is thinking of adding a Pi Zero W tot eh QC) additionally by adding the QC to the herd it can hand in data in the form of peudo-LiDAR reads (subject to object definition) so I'm thinking a member that is a Sensor but not processor/driver(although that could be an extension)/Dest_setter(ext)/display(more ext) so suitable certs would need to be considered

**Comment by SamanthaDawsonBanks** [comment]
as part of an (upcoming) interface refactor the public part of the API should self create, but if anyone spots a function that should be part of the public API please comment it here

**Comment by SamanthaDawsonBanks** [comment]
leader needs to provide:
setDestination(waypoint (x,y))
get"Data"() : model //for views

some MVC register/deregister [expand]
some rmi register/deregister [expand]

**Comment by SamanthaDawsonBanks** [comment]
![2018-03-09-13 01](https://user-images.githubusercontent.com/25463297/37253362-c3dd9e42-2528-11e8-961d-1f05579b650d.png)

**Comment by SamanthaDawsonBanks** [comment]
there is a planned interface shuffle coming up so we will fold this into that

**Comment by SamanthaDawsonBanks** [comment]
interface shuffle done (well PR'ed)
API = implement the interfaces
