### ISSUE TITLE
All classes behave as they should - formal proof

### ISSUE THREAD

**Issue by CFuterman** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#91]

**Comment by stevempope** [comment]
Formal Proof maybe should be pushed back, not sure if we will be ready in time or in the right place.

**Comment by SamanthaDawsonBanks** [comment]
bumped to M3 (maybe even M4?) some of it can come from JUnit as if a collection then the JUnit will be:
x is empty
x.add(b)
x now contains b
b < x.pop
x is now empty again

and the formal will be much the same reflecting set theory
