### ISSUE TITLE
Integration Testing

### ISSUE THREAD

**Issue by CFuterman** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#92]

**Comment by SamanthaDawsonBanks** [comment]
C:
waypoint
path
pathItem
all done

**Comment by SamanthaDawsonBanks** [comment]
J:
Waypoint
Map
Path
LinkedItem
Pathfinding
Heuristics
(Proto)GUI

Done

**Comment by SamanthaDawsonBanks** [comment]
once I fix the Member>Leader>Herd stuff (Wednesday/Thursday) we should be at a point where all test will be done from the base MemberMain as per integration testing

**Comment by SamanthaDawsonBanks** [comment]
ok, so, a member fires up forms a herd, elects a leader, the member registers with the leader and the lead requests a lidar read, that read in then added to the herd map and the members (need to add code for view) get notified and request updated herd data...

 I think that is the full startup and data cycle??
