### ISSUE TITLE
Map Test

### ISSUE THREAD

**Issue by HarryWJackson1996** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#93]
As previously mentioned in our meeting I was having problems creating a map to test the A* search against as I struggle implementing code when I cant check if it actually works. Any thoughts on how you think a test map should be implemented?

**Comment by SamanthaDawsonBanks** [comment]
I will rough together a test one asap sorry that it has held you up :)

**Comment by SamanthaDawsonBanks** [comment]
#96 for the dummy map, just hacking together a map that "works"

**Comment by HarryWJackson1996** [comment]
Ok thanks thats great! So based on whats stated in #96, there is a dummy map but it currently cant be used to test the A* until the map has been implemented?

**Comment by SamanthaDawsonBanks** [comment]
correct i will be sorting the map today

**Comment by HarryWJackson1996** [comment]
ah great, thanks for the help! Its really appreciated! :)

**Comment by SamanthaDawsonBanks** [comment]
map and test are both in #103

**Comment by SamanthaDawsonBanks** [comment]
oh and the test includes the presentation test map
