### ISSUE TITLE
Main Class

### ISSUE THREAD

**Issue by stevempope** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#94]
Hi All,

We need a method Main which fires up on the Pi. I was thinking of feeding the program a list of abilities for research purposes at the minute.

For each ability in the list provided to the program "String [] args" or Enum [] args, fire up a single member object with those abilities.

That member becomes the leader of its own Herd. Main should then have some methods that handle data recieved and pass them to the right object. It should also poll to see if there are any neighbouring herds, and call to join if conditions are met.

Any thoughts? I know the outline is a little vague but just thinking about how we approach main as a "Controller"?

**Comment by SamanthaDawsonBanks** [comment]
If you abstract "view" to mean Input/Output
I would go with MVC as LiDAR / motors in the "view/controller"
maps, paths and path-finding in the "Model"
all over the Client/Server pattern
so...
![image](https://user-images.githubusercontent.com/25463297/36593438-9df7ac5c-1891-11e8-966f-7b56f46049b8.png)
with green as Client and orange as Server?

**Comment by SamanthaDawsonBanks** [comment]
encompasses / related to #60

**Comment by stevempope** [comment]
Ok thanks for the input Dave. Ryan can we arrange to meet this week and talk about this structure?

**Comment by SamanthaDawsonBanks** [comment]
based on the proto herd life-cycle; and assuming that #74 = process
I think:
State 1 will be the Member Process [MemberMain] starting up (with appropriate abilities info) and that including the transition to State 2 {single member in a herd with no leader}

State 2 (or 2a) *MUST* result in an election and that election will spawn the Leader Process [LeaderMain] allowing for a transition to 3/3a

State 4 {herd merge} need that the two LeaderMain processes (Master and Slave) communicate and that Slave (the one closing its herd and joining the other) passes its dataset to Master (the one that will be accepting the new member) - Slave's Leader Process will then watch over the transfer of that bots Member Process to being a member of Masters herd - and then Slave's Leader Process will terminate


Does that sound about right?

**Comment by SamanthaDawsonBanks** [comment]
with all this said:
I think we should refactor... the Pi Ui packages into something more Server/Client or M/CV
comments?

**Comment by stevempope** [comment]
Closing this as we have agreed on a structure and a Main class for the robot now exists in #110
